### ISSUE TITLE
Bad URI error in case of missing slash in wp-content path on webpage

### ISSUE THREAD

**Issue by TheRawman** [wpscanteam/wpscan#1154]
Recently I faced an issue with one particular WordPress blog, which has following code in the hrefs:
_href="wp-content/themes/sl/style.css?ver=1.0.8"_

Due to the missing slash in wp-content path site enumeration fails with the error: Bad URI.
Below is debugger trace messages:
```
[+] WordPress version 4.9.1 identified from advanced fingerprinting
 | Released: 2017-11-29
 | Changelog: https://codex.wordpress.org/Version_4.9.1

[!] bad URI(is not URI?): href="wp-content/themes/sl/
[!] Trace:
[!] /.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split'
/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/uri/rfc3986_parser.rb:117:in `convert_to_uri'
/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/uri/generic.rb:1099:in `merge'
/Soft/Tools/wpscan/lib/common/models/wp_theme.rb:32:in `forge_uri'
/Soft/Tools/wpscan/lib/common/models/wp_item.rb:37:in `initialize'
/Soft/Tools/wpscan/lib/common/models/wp_theme/findable.rb:35:in `new'
/Soft/Tools/wpscan/lib/common/models/wp_theme/findable.rb:35:in `find_from_css_link'
/Soft/Tools/wpscan/lib/common/models/wp_theme/findable.rb:13:in `block in find'
/Soft/Tools/wpscan/lib/common/models/wp_theme/findable.rb:12:in `each'
/Soft/Tools/wpscan/lib/common/models/wp_theme/findable.rb:12:in `find'
/Soft/Tools/wpscan/lib/wpscan/wp_target.rb:94:in `theme'
./wpscan.rb:281:in `main'
./wpscan.rb:534:in `<main>'
./wpscan.rb:525: `bad URI(is not URI?): href="wp-content/themes/sl/' (URI::InvalidURIError)
	from ./wpscan.rb:531:in `main'
	from ./wpscan.rb:534:in `<main>'
./wpscan.rb:525:    exit(1)
```

I'm using wpscan Version 2.9.4-dev , but I can reproduce this issue on other platform and wpscan versions.
I've found cripple workaround - changed #{wp_content_dir} to the exact path '/wp-content/' and it helped to go one step forward. Then wpscan didn't enumerate plugins on the website:
```
[+] Enumerating plugins from passive detection ...
[+] No plugins found
```

**Comment by erwanlr** [comment]
Do you also have the error with the v3 ?

Could you send us the url of the blog, at team at wpscan dot org please ?

**Comment by TheRawman** [comment]
No, with v3 I don't get this error ( Bad URI). The wpscan 3.0.8 just can't go farther than "unable to identify wp-content dir":
```
ruby -rdebug ./bin/wpscan --url blog.target --force 
.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/x86_64-darwin16/continuation.bundle: warning: callcc is obsolete; use Fiber instead
Debug.rb
Emacs support available.

./bin/wpscan:3:require 'wpscan'
(rdb:1) n
./bin/wpscan:5:WPScan::Scan.new do |s|
(rdb:1) n
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.0.8
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

Scan Aborted: Unable to identify the wp-content dir, please supply it with --wp-content-dir
.rvm/gems/ruby-2.4.1/gems/cms_scanner-0.0.38.2/lib/cms_scanner.rb:134:        exit(run_error_exit_code) if run_error
(rdb:1) n
.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/utility/at_exit.rb:49:                         at_exit { runner }
(rdb:1) n
```
If I do specify --wp-content option I get an exception:
```
/bin/wpscan --url blog.target/ --force --wp-content-dir wp-content
#a logo was cut#
        WordPress Security Scanner by the WPScan Team
                       Version 3.0.8
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

[+] URL: http://blog.target/
[+] Started: Mon Dec 11 09:03:03 2017

Interesting Finding(s):

[+] http://blog.target/
 | Interesting Entries:
 |  - Server: Apache/2.2.22 (Debian)
 |  - X-Powered-By: PHP/5.6.30-1~dotdeb+7.1
 |  - X-Adblock-Key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANnylWw2vLY4hUn9w06zQKbhKBfvjFUCsdFlb6TdQhxb9RXWXuI4t31c+o8fYOv/s8q1LGPga3DE1L/tHU4LENMCAwEAAQ==_BvP8zSsJbemFfBJNZ/+PtPTLfw1J6wZbQEnEWO2EJ9qLpOudbIoJGqDQv3A2cPhpGIa8+gvs4CIV0X9N4ymEgw==
 |  - Cneonction: close
 | Found By: Headers (Passive Detection)
 | Confidence: 100%

[+] http://blog.target/robots.txt
 | Found By: Robots Txt (Aggressive Detection)
 | Confidence: 100%

[+] This site seems to be a multisite
 | Found By: Direct Access (Aggressive Detection)
 | Confidence: 100%
 | Reference: http://codex.wordpress.org/Glossary#Multisite
 
Fingerprinting the version - Time: 00:00:00 <===========================================================================================================================> (304 / 304) 100.00% Time: 00:00:00
Scan Aborted: undefined method `confidence' for false:FalseClass
```
Perhaps the blog is somehow configured that way so it's blocking WordPress enumeration techniques. I've sent an URL of the page to the e-mail provided.

**Comment by erwanlr** [comment]
I was able to reproduce the error from the v2, but not with the v3.


From the v3, the interesting entries I got don't match the one you pasted here. So we either have different targets or something else is going on :x

Interesting Entries I got:

From the first target in the email:
```
[+] https://REDACTED/
 | Interesting Entries:
 |  - Server: nginx
 |  - X-Powered-By: PHP/7.1.7
 | Found By: Headers (Passive Detection)
 | Confidence: 100%
```

From the second one:
```
[+] https://REDACTED/
 | Interesting Entries:
 |  - Server: nginx-reuseport/1.13.4
 |  - X-Powered-By: PHP/7.0.19
 | Found By: Headers (Passive Detection)
 | Confidence: 100%
```

**Comment by erwanlr** [comment]
Issue has been fixed in the v2.

If you could confirm the target you used for the v3, or re-scan using the ```-v``` option, that would help try to fix it as well :)

**Comment by TheRawman** [comment]
Sorry for delayed reply.

wpscan 2 work fine now. I can not reproduce the issue with wpscan-3, probably did something wrong first time.

Thank you for your assistance and great software!

**Comment by erwanlr** [comment]
Great, thanks for the update :)
