### ISSUE TITLE
Could not find ffi-1.9.18

### ISSUE THREAD

**Issue by baglio** [wpscanteam/wpscan#1166]
Wpscan can't be executed and this error is prompted:

```
Could not find ffi-1.9.18 in any of the sources
Run `bundle install` to install missing gems.
```

**My configuration**:

- macOS 10.12.6
- ruby 2.5.0p0 (via rbenv)
- wpscan installed via Brew

**Running `bundle install` gives me the following message**:

```
Ignoring executable-hooks-1.3.2 because its extensions are not built. Try: gem pristine executable-hooks --version 1.3.2
Ignoring gem-wrappers-1.3.2 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.3.2
Could not locate Gemfile
```

**Comment by erwanlr** [comment]
When do you have this error ?
- When trying to install wpscan via brew or;
- When running wpscan

Did you try ```gem install ffi``` ?

**Comment by baglio** [comment]
The error shows up when I try to run wpscan. The installation with brew went smooth. 

Yes, I did `gem install ffi` and had no problem with the installation.

**Comment by erwanlr** [comment]
Just tried to install via brew and got such error while installing, as a warning in the postinstall process (seems like to be related to permissions in the home folder). So there is definitely something wrong with either their install process or my environment, and yours.

So, 3 solutions:
- Try to fix the brew warning when installing wpscan with it
- Install wpscan v2 from the git repository (see readme)
- Install wpscan v3 with ```gem install wpscan```

**Comment by kontur** [comment]
Had the/a similar problem.

Retrying the brew postinstall 
```
$ brew postinstall wpscan
==> Postinstalling wpscan
==> /usr/local/Cellar/wpscan/2.9.3_5/bin/wpscan --update
Last 15 lines from /Users/johannes/Library/Logs/Homebrew/wpscan/post_install.01.wpscan:

`/Users/johannes` is not writable.
Bundler will use `/tmp/bundler/home/johannes' as your home directory temporarily.
/usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find ffi-1.9.18 in any of the sources (Bundler::GemNotFound)
	from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `map!'
	from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `materialize'
	from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
	from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
	from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
	from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
	from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
	from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
	from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

Why does it want to mess around in my user dir? 

I installed as gem, but the brew install certainly has issues.

**Comment by oussjarrouse** [comment]
I am also receiving the same error!!
- macOS: 10.13.4
- Homebrew 1.6.2
- Homebrew/homebrew-core (git revision 22511f; last commit 2018-04-23)
- wpscan formula 2.9.3_5
- ruby formula 2.5.1

**Comment by jpgninja** [comment]
Looks like I'm getting a similar error to @kontur but re-linking `ruby` didn't seem to solve the issue, or – at least – I wasn't able to figure it out.

Have tried re-linking ruby, reinstalling the `ffi` gem (including an `gem uninstall -a`), re-installing homebrew, as well as _many_ other loosely related ideas I worried might've been causing issued, like updating `rvm`, `ruby`, etc.

Homebrew spits back the following error when I run `brew install --verbose --debug wpscan`:

```
[...]
==> Finishing up
ln -s ../Cellar/wpscan/2.9.3_5/bin/wpscan wpscan
/usr/bin/sandbox-exec -f /tmp/homebrew20180606-54353-1ntxchr.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wpscan.rb --verbose --debug
/usr/local/Homebrew/Library/Homebrew/postinstall.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wpscan.rb
==> /usr/local/Cellar/wpscan/2.9.3_5/bin/wpscan --update
`/Users/chris` is not writable.
Bundler will use `/tmp/bundler/home/user' as your home directory temporarily.
/usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find ffi-1.9.18 in any of the sources (Bundler::GemNotFound)
  from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `map!'
  from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `materialize'
  from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
  from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
  from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
  from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
  from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
  from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
  from /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `<top (required)>'
  from /Users/chris/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from /Users/chris/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall wpscan`
==> Failed executing: /usr/local/Cellar/wpscan/2.9.3_5/bin/wpscan --update
/usr/local/Homebrew/Library/Homebrew/formula.rb:1854:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1792:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1792:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wpscan.rb:44:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:999:in `block (2 levels) in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:856:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:998:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:990:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:16:in `<main>'
==> Caveats
Logs are saved to /usr/local/var/cache/wpscan/log.txt by default.
==> Summary
🍺  /usr/local/Cellar/wpscan/2.9.3_5: 4,427 files, 43.9MB
```

For what it's worth, I tried installing via gem (`gem install wpscan`) and manually (`git`, `cd`, then `gem install bundler && bundle install`), which didn't prove fruitful, either.

**Comment by FireFart** [comment]
If you have docker installed and know how to use it you can use the docker image https://hub.docker.com/r/wpscanteam/wpscan/

**Comment by denostr** [comment]
Solved this problem for myself. wpscan and ruby was installed latest versions by brew, but when i running wpscan, it used non brew ruby. Fixed by running ```brew link ruby```

**Comment by mhborujerdi** [comment]
Hello, You should install the latest version of CommandLineTools for Xcode to fix this issue.
