### ISSUE TITLE
Typhoeus error: Stack level too deep (systemstackerror)

### ISSUE THREAD

**Issue by Viss** [wpscanteam/wpscan#1204]
Newest version of wpscan, running on ubuntu + rvm, ruby version 2.5.1
Aiming wpscan at a known wordpress blog, I get the following stack trace:

```
Traceback (most recent call last):
	8741: from ./wpscan.rb:626:in `<main>'
	8740: from ./wpscan.rb:164:in `main'
	8739: from /home/viss/tools/wpscan/lib/wpscan/web_site.rb:93:in `redirection'
	8738: from /home/viss/tools/wpscan/lib/wpscan/web_site.rb:93:in `redirection'
	8737: from /home/viss/tools/wpscan/lib/wpscan/web_site.rb:93:in `redirection'
	8736: from /home/viss/tools/wpscan/lib/wpscan/web_site.rb:93:in `redirection'
	8735: from /home/viss/tools/wpscan/lib/wpscan/web_site.rb:93:in `redirection'
	8734: from /home/viss/tools/wpscan/lib/wpscan/web_site.rb:93:in `redirection'
	 ... 8729 levels...
	   4: from /home/viss/.rvm/gems/ruby-2.5.1@wpscan/gems/typhoeus-1.3.0/lib/typhoeus/request.rb:204:in `map'
	   3: from /home/viss/.rvm/gems/ruby-2.5.1@wpscan/gems/typhoeus-1.3.0/lib/typhoeus/request.rb:204:in `block in hashable_string_for'
	   2: from /home/viss/.rvm/gems/ruby-2.5.1@wpscan/gems/typhoeus-1.3.0/lib/typhoeus/request.rb:204:in `hashable_string_for'
	   1: from /home/viss/.rvm/gems/ruby-2.5.1@wpscan/gems/typhoeus-1.3.0/lib/typhoeus/request.rb:204:in `map'
/home/viss/.rvm/gems/ruby-2.5.1@wpscan/gems/typhoeus-1.3.0/lib/typhoeus/request.rb:204:in `block in hashable_string_for': stack level too deep (SystemStackError)
```

A previous issue (from 2013?) explains that this error is becuase the site isn't a wordpress blog, but it appears that issue is resolved. I think in this case the site is, in fact, a wordpress blog, but it may have some kind of security measures (I tried to hit /wp-admin and got a 403, but robots.txt is available and makes it clear there's a wordpress blog there).

Any advice would be greatly appreciated!

**Comment by FireFart** [comment]
This looks like a endless redirection and typhoeus is not erroring out after a certain amount of redirects. Can you please try to use a proxy like burp with wpscan to see the response and post it here (anonymized) so we can try to reproduce it? IIf it's a plain http site you could also watch with wireshark

**Comment by FireFart** [comment]
Looks like we need to add a check here, it's not typhoeus automatic redirect: https://github.com/wpscanteam/wpscan/blob/master/lib/wpscan/web_site.rb#L81

**Comment by FireFart** [comment]
Ok so there are two issues here:
- we need to add a bail out function on redirects to eliminate infinite redirects
- currently we only handle redirects on the same domain. In this case we need to check if the redirect itself is an url to another domain

**Comment by ArSn** [comment]
👋🏻  Apologies for the very late response.

It turns out the recursive thing in that `WPScan::WebSite#redirection` method at fault here has been refactored quite some time ago already; instead we now just let Typhoeus handle the redirect following.

That being said, I found a few places where we did not pass in a maximum number of redirects to follow, and even though cURL probably catches that with recursion detection, I've added some more limitations in https://github.com/wpscanteam/wpscan/pull/2022 just to be extra safe.
