### ISSUE TITLE
3.3.1: unable to detect wp website

### ISSUE THREAD

**Issue by blshkv** [wpscanteam/wpscan#1221]
I'm testing the tool on a random website in passive mode:
```
wpscan --verbose --url www.kdpof.com --disable-tls-checks
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.3.1
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

Scan Aborted: The remote website is up, but does not seem to be running WordPress.
Trace: /usr/lib64/ruby/gems/2.3.0/gems/wpscan-3.3.1/app/controllers/core.rb:74:in `check_wordpress_state'
/usr/lib64/ruby/gems/2.3.0/gems/wpscan-3.3.1/app/controllers/core.rb:59:in `before_scan'
/usr/lib64/ruby/gems/2.3.0/gems/cms_scanner-0.0.40.1/lib/cms_scanner/controllers.rb:42:in `each'
/usr/lib64/ruby/gems/2.3.0/gems/cms_scanner-0.0.40.1/lib/cms_scanner/controllers.rb:42:in `run'
/usr/lib64/ruby/gems/2.3.0/gems/cms_scanner-0.0.40.1/lib/cms_scanner.rb:103:in `run'
/usr/lib64/ruby/gems/2.3.0/gems/wpscan-3.3.1/bin/wpscan:15:in `block in <top (required)>'
/usr/lib64/ruby/gems/2.3.0/gems/cms_scanner-0.0.40.1/lib/cms_scanner.rb:94:in `initialize'
/usr/lib64/ruby/gems/2.3.0/gems/wpscan-3.3.1/bin/wpscan:5:in `new'
/usr/lib64/ruby/gems/2.3.0/gems/wpscan-3.3.1/bin/wpscan:5:in `<top (required)>'
/usr/bin/wpscan:9:in `load'
/usr/bin/wpscan:9:in `<main>'
```

but website is clearly running wp. See ```https://www.kdpof.com/wp-content```

Can you confirm it? I can provide any other info if required.

**Comment by blshkv** [comment]
btw, there is the second issue with HTTPS connection, the cert is valid but the tool is unable to connect by default

**Comment by erwanlr** [comment]
Seems like there is a WAF/security plugin enabled. Use --random-user-agent ;)

Furthermore, the default detections are not all passive, if you really want passive stuff, go for --stealthy (which include the --random-user-agent)

Finally, regarding the certificate, either update curl or your certificate list if needed, I didn't have to provide the --disable-tls-checks to check the blog you provided.

**Comment by blshkv** [comment]
ok, true. Thanks! Both curl and wget reports an SSL error for me. I'll figure it out

**Comment by blshkv** [comment]
ok, I have just found that somebody forked it last week
https://github.com/iknowjason/voiphopper/commits/master

They have fixed few bugs. Let's see how long they will last
