### ISSUE TITLE
Scan Aborted: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by FireFart** [wpscanteam/wpscan#1244]
@erwan:

```
docker run -u root -v $(pwd):/results/ --rm -it wpscanteam/wpscan --url http://ethicalhack3r.co.uk -e vp,vt,cb,dbe,u,m --wp-content-dir --format json -o /results/test.json
```

```

[i] No Medias Found.

Scan Aborted: undefined method `[]' for nil:NilClass
```

**Comment by erwanlr** [comment]
Given that the --wp-content-dir is an OptString, anything is taken, even --format

Not sure how to handle that other than checking for '--' at the beginning of its value, but that would be in the WPScan code, not OptParseValidator

**Comment by erwanlr** [comment]
The error causing the scan aborted is related app/finders/users/oembed_api.rb:26:in `aggressive'. Will have a look later

**Comment by FireFart** [comment]
ok :)

I reran the scan with -v and here is the stacktrace of the error:
```text
Scan Aborted: undefined method `[]' for nil:NilClass
Trace: /usr/local/bundle/gems/wpscan-3.3.2/app/finders/users/oembed_api.rb:26:in `aggressive'
/usr/local/bundle/gems/cms_scanner-0.0.40.2/lib/cms_scanner/finders/base_finders.rb:29:in `run_finder'
/usr/local/bundle/gems/cms_scanner-0.0.40.2/lib/cms_scanner/finders/same_type_finders.rb:14:in `block (2 levels) in run'
/usr/local/bundle/gems/cms_scanner-0.0.40.2/lib/cms_scanner/finders/same_type_finders.rb:13:in `each'
/usr/local/bundle/gems/cms_scanner-0.0.40.2/lib/cms_scanner/finders/same_type_finders.rb:13:in `block in run'
/usr/local/bundle/gems/cms_scanner-0.0.40.2/lib/cms_scanner/finders/same_type_finders.rb:12:in `each'
/usr/local/bundle/gems/cms_scanner-0.0.40.2/lib/cms_scanner/finders/same_type_finders.rb:12:in `run'
/usr/local/bundle/gems/cms_scanner-0.0.40.2/lib/cms_scanner/finders/independent_finder.rb:19:in `find'
/usr/local/bundle/gems/cms_scanner-0.0.40.2/lib/cms_scanner/finders/independent_finder.rb:10:in `find'
/usr/local/bundle/gems/wpscan-3.3.2/lib/wpscan/target.rb:91:in `users'
/usr/local/bundle/gems/wpscan-3.3.2/app/controllers/enumeration/enum_methods.rb:170:in `enum_users'
/usr/local/bundle/gems/wpscan-3.3.2/app/controllers/enumeration.rb:23:in `run'
/usr/local/bundle/gems/cms_scanner-0.0.40.2/lib/cms_scanner/controllers.rb:43:in `each'
/usr/local/bundle/gems/cms_scanner-0.0.40.2/lib/cms_scanner/controllers.rb:43:in `run'
/usr/local/bundle/gems/cms_scanner-0.0.40.2/lib/cms_scanner.rb:103:in `run'
/usr/local/bundle/gems/wpscan-3.3.2/bin/wpscan:15:in `block in <top (required)>'
/usr/local/bundle/gems/cms_scanner-0.0.40.2/lib/cms_scanner.rb:94:in `initialize'
/usr/local/bundle/gems/wpscan-3.3.2/bin/wpscan:5:in `new'
/usr/local/bundle/gems/wpscan-3.3.2/bin/wpscan:5:in `<top (required)>'
/usr/local/bundle/bin/wpscan:23:in `load'
/usr/local/bundle/bin/wpscan:23:in `<main>'

```

**Comment by enderlh** [comment]
I have a pretty similar error:
```
Scan Aborted: undefined method `capitalize' for nil:NilClass
Trace: (erb):2:in `render'
/usr/lib/ruby/2.5.0/erb.rb:876:in `eval'
/usr/lib/ruby/2.5.0/erb.rb:876:in `result'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.0.41.0/lib/cms_scanner/formatter.rb:94:in `render'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.0.41.0/lib/cms_scanner/formatter.rb:82:in `output'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.0.41.0/lib/cms_scanner/controller.rb:73:in `output'
/usr/share/rubygems-integration/all/gems/wpscan-3.4.0/app/controllers/wp_version.rb:22:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.0.41.0/lib/cms_scanner/controllers.rb:43:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.0.41.0/lib/cms_scanner/controllers.rb:43:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.0.41.0/lib/cms_scanner.rb:137:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.4.0/bin/wpscan:15:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.0.41.0/lib/cms_scanner.rb:128:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.4.0/bin/wpscan:5:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.4.0/bin/wpscan:5:in `<top (required)>'
/usr/bin/wpscan:23:in `load'
/usr/bin/wpscan:23:in `<main>'
```

**Comment by erwanlr** [comment]
v3.4.1 released to fix the issue @enderlh (see https://github.com/wpscanteam/wpscan/issues/1264)

**Comment by enderlh** [comment]
> v3.4.1 released to fix the issue @enderlh (see #1264)

It's working! Thanks.

**Comment by Cloufish** [comment]
Having the same issue. 2 years have passed, is there a solution other than ```wpscan --update``` if it's not working?
```
Scan Aborted: undefined method `[]' for nil:NilClass
Trace: /usr/share/rubygems-integration/all/gems/wpscan-3.8.1/app/finders/db_exports/known_locations.rb:43:in `potential_urls'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.1/app/finders/db_exports/known_locations.rb:20:in `aggressive'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/finders/base_finders.rb:31:in `run_finder'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/finders/same_type_finders.rb:16:in `block (2 levels) in run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/finders/same_type_finders.rb:15:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/finders/same_type_finders.rb:15:in `block in run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/finders/same_type_finders.rb:14:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/finders/same_type_finders.rb:14:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/finders/independent_finder.rb:21:in `find'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/finders/independent_finder.rb:12:in `find'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.1/lib/wpscan/target.rb:88:in `db_exports'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.1/app/controllers/enumeration/enum_methods.rb:167:in `enum_db_exports'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.1/app/controllers/enumeration.rb:17:in `block in run'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.1/app/controllers/enumeration.rb:16:in `each'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.1/app/controllers/enumeration.rb:16:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/controllers.rb:50:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/controllers.rb:50:in `block in run'
/usr/lib/ruby/2.7.0/timeout.rb:78:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/controllers.rb:45:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/scan.rb:24:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.1/bin/wpscan:17:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.1/bin/wpscan:6:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.1/bin/wpscan:6:in `<top (required)>'
/usr/bin/wpscan:23:in `load'
/usr/bin/wpscan:23:in `<main>'
```

**Comment by erwanlr** [comment]
That's not the same issue.

What's the `--url` argument you supplied ? Seems like Addressable can't determine the host

**Comment by Cloufish** [comment]
> That's not the same issue.
> 
> What's the `--url` argument you supplied ? Seems like Addressable can't determine the host
I'll put the whole command just in case
```wpscan --enumerate --url http://dc-2 -v```

**Comment by erwanlr** [comment]
@Cloufish This has been fixed in master and the docker image. A new minor version will be released once the specs are finished.
