### ISSUE TITLE
Scan Aborted: Unable to ...... (Timeout was reached)

### ISSUE THREAD

**Issue by M0dred** [wpscanteam/wpscan#1252]
wpscan --update
[i] Updating the Database ...
Scan Aborted: Unable to get https://data.wpscan.org/plugins.json.sha512 (Timeout was reached)
Trace: /usr/share/rubygems-integration/all/gems/wpscan-3.4.0/lib/wpscan/db/updater.rb:83:in `remote_file_checksum'
/usr/share/rubygems-integration/all/gems/wpscan-3.4.0/lib/wpscan/db/updater.rb:135:in `block in update'
/usr/share/rubygems-integration/all/gems/wpscan-3.4.0/lib/wpscan/db/updater.rb:133:in `each'
/usr/share/rubygems-integration/all/gems/wpscan-3.4.0/lib/wpscan/db/updater.rb:133:in `update'
/usr/share/rubygems-integration/all/gems/wpscan-3.4.0/app/controllers/core.rb:45:in `update_db'
/usr/share/rubygems-integration/all/gems/wpscan-3.4.0/app/controllers/core.rb:55:in `before_scan'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.0.41.0/lib/cms_scanner/controllers.rb:42:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.0.41.0/lib/cms_scanner/controllers.rb:42:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.0.41.0/lib/cms_scanner.rb:137:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.4.0/bin/wpscan:15:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.0.41.0/lib/cms_scanner.rb:128:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.4.0/bin/wpscan:5:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.4.0/bin/wpscan:5:in `<top (required)>'
/usr/bin/wpscan:23:in `load'
/usr/bin/wpscan:23:in `<main>'

gem -v
2.7.6

wpscan --version
Current Version: 3.4.0

ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

uname -a
Linux kali 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64 GNU/Linux

**Comment by M0dred** [comment]
Now is all right. Updated
Maybe the network instability.
However,Thanks.
