### ISSUE TITLE
WPScan fails to start with error undefined symbol: rmpd_util_str_to_d 

### ISSUE THREAD

**Issue by digininja** [wpscanteam/wpscan#1283]
### Subject of the issue
WPScan fails to run and gives the error below.

Duplicate of this but with more info: https://github.com/wpscanteam/wpscan/issues/1272

### Your environment
* Version of WPScan: 3.4.3
* Version of Ruby: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
* Operating System (OS): Ubuntu 18.04

### Steps to reproduce
Installed the wpscan gem then ran it

### Expected behavior
Should work

### Actual behavior
Doesn't work

```
$ wpscan 
Traceback (most recent call last):
        30: from /home/robin/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
        29: from /home/robin/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
        28: from /home/robin/.rvm/gems/ruby-2.5.3/bin/wpscan:23:in `<main>'
        27: from /home/robin/.rvm/gems/ruby-2.5.3/bin/wpscan:23:in `load'
        26: from /home/robin/.rvm/gems/ruby-2.5.3/gems/wpscan-3.4.3/bin/wpscan:3:in `<top (required)>'
        25: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        24: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        23: from /home/robin/.rvm/gems/ruby-2.5.3/gems/wpscan-3.4.3/lib/wpscan.rb:5:in `<top (required)>'
        22: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        21: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        20: from /home/robin/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/all.rb:5:in `<top (required)>'
        19: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        18: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        17: from /home/robin/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/core_ext.rb:3:in `<top (required)>'
        16: from /home/robin/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/core_ext.rb:3:in `each'
        15: from /home/robin/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/core_ext.rb:4:in `block in <top (required)>'
        14: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        13: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        12: from /home/robin/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/core_ext/object.rb:13:in `<top (required)>'
        11: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        10: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         9: from /home/robin/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/core_ext/object/json.rb:8:in `<top (required)>'
         8: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         7: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         6: from /home/robin/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/core_ext/big_decimal/conversions.rb:4:in `<top (required)>'
         5: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         4: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         3: from /home/robin/.rvm/gems/ruby-2.5.3/gems/bigdecimal-1.4.3/lib/bigdecimal/util.rb:9:in `<top (required)>'
         2: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
         1: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require': /home/robin/.rvm/gems/ruby-2.5.3/gems/bigdecimal-1.4.3/lib/bigdecimal/util.so: undefined symbol: rmpd_util_str_to_d - /home/robin/.rvm/gems/ruby-2.5.3/gems/bigdecimal-1.4.3/lib/bigdecimal/util.so (LoadError)
```

Running it from the latest GitHub source gives the same error.

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.

Things you have tried (where relevant):

* Update WPScan to the latest version [x ]
* Update Ruby to the latest version [x ]
* Ensure you can reach the target site using cURL [ ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [x ]

**Comment by erwanlr** [comment]
This is due to a bug in the require method of Ruby 2.5: https://bugs.ruby-lang.org/issues/15500. Fix should land in the next minor version of Ruby.

**Comment by digininja** [comment]
A downgrade to 2.4.5 fixed it.

Worth putting a check in when the app starts to look at the version
and report on the bug?

**Comment by erwanlr** [comment]
I would have excluded the bugged versions in the .gemspec (via the required_ruby_version) if this was possible, but it's not unfortunately. Furthermore, the issue is not present in all OS (e.g I don't have it with Ruby 2.5.3 on Debian).

I will add something about it in the Readme though.
