### ISSUE TITLE
can't update

### ISSUE THREAD

**Issue by huitc** [wpscanteam/wpscan#1339]
`$ wpscan --update`
```
Traceback (most recent call last):
        24: from /data/data/com.termux/files/usr/bin/wpscan:23:in `<main>'
        23: from /data/data/com.termux/files/usr/bin/wpscan:23:in `load'
        22: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/wpscan-3.5.3/bin/wpscan:4:in `<top (required)>'
        21: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        20: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        19: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/wpscan-3.5.3/lib/wpscan.rb:7:in `<top (required)>'
        18: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        17: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        16: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/all.rb:5:in `<top (required)>'
        15: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        14: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        13: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/core_ext.rb:3:in `<top (required)>'
        12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/core_ext.rb:3:in `each'
        11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/core_ext.rb:4:in `block in <top (required)>'
        10: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         8: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/core_ext/big_decimal.rb:3:in `<top (required)>'
         7: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         6: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         5: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/core_ext/big_decimal/conversions.rb:4:in `<top (required)>'
         4: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         3: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         2: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `<top (required)>'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen failed: cannot locate symbol "rmpd_util_str_to_d" referenced by "/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so"... - /data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so (LoadError)
```

**Comment by huitc** [comment]
`Linux localhost 4.4.78-perf-g50f7ec6 #1 SMP PREEMPT Thu Apr 11 04:40:18 CST 2019 aarch64 Android`
```
$ gem update wpscan
Updating installed gems
Nothing to update
```

**Comment by huitc** [comment]
`bundle install`
```
...
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from rubocop:
Performance Cops will be removed from RuboCop 0.68. Use rubocop-performance gem instead.

Put this in your Gemfile.

```rb
gem 'rubocop-performance'
```

And then execute:

```sh
$ bundle install
```

Put this into your .rubocop.yml.

```yaml
require: rubocop-performance
```

More information: https://github.com/rubocop-hq/rubocop-performance
```

**Comment by erwanlr** [comment]
This is an issue you should report to Termux.

I've found that someone had a similar issue with Metasploit, and here was the recommendation (no idea if it works though): https://github.com/rapid7/metasploit-framework/issues/11492#issuecomment-468285757
