### ISSUE TITLE
can't run wpscan.... t.t

### ISSUE THREAD

**Issue by huitc** [wpscanteam/wpscan#1355]
I'm using this app termux
https://play.google.com/store/apps/details?id=com.termux
```
gem install wpscan
wpscan
```
```
Traceback (most recent call last):
        24: from /data/data/com.termux/files/usr/bin/wpscan:23:in `<main>'                                            23: from /data/data/com.termux/files/usr/bin/wpscan:23:in `load'
        22: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/wpscan-3.5.3/bin/wpscan:4:in `<top (required)>'
        21: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
...
/data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen failed: cannot locate symbol "rmpd_util_str_to_d" referenced by "/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so"... - /data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so (LoadError)
```

**Comment by erwanlr** [comment]
Same as your previous issue https://github.com/wpscanteam/wpscan/issues/1339. Contact Termux
