### ISSUE TITLE
how do I fix this error?

### ISSUE THREAD

**Issue by huitc** [wpscanteam/wpscan#1370]
```
$ wpscan
Traceback (most recent call last):
        24: from /data/data/com.termux/files/usr/bin/wpscan:23:in `<main>'
        23: from /data/data/com.termux/files/usr/bin/wpscan:23:in `load'
        22: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/wpscan-3.6.0/bin/wpscan:4:in `<top (required)>'
        21: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        20: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        19: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/wpscan-3.6.0/lib/wpscan.rb:7:in `<top (required)>'
        18: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        17: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        16: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/all.rb:5:in `<top (required)>'
        15: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        14: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        13: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/core_ext.rb:3:in `<top (required)>'
        12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/core_ext.rb:3:in `each'
        11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/core_ext.rb:4:in `block in <top (required)>'
        10: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         8: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/core_ext/big_decimal.rb:3:in `<top (required)>'
         7: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         6: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         5: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/core_ext/big_decimal/conversions.rb:4:in `<top (required)>'
         4: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         3: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         2: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `<top (required)>'
         1: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen failed: cannot locate symbol "rmpd_util_str_to_d" referenced by "/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so"... - /data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so (LoadError)
$ 
```

**Comment by huitc** [comment]
https://play.google.com/store/apps/details?id=com.termux

**Comment by erwanlr** [comment]
Like your two previous issues about the same thing.

https://github.com/wpscanteam/wpscan/issues/1355
https://github.com/wpscanteam/wpscan/issues/1339
