### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by huitc** [wpscanteam/wpscan#1375]
```
xxxxx@DESKTOP-xxxxx:~/wpscan$ wpscan
\Traceback (most recent call last):
        2: from /home/xxxxx/.rvm/gems/ruby-2.6.2/bin/wpscan:23:in `<main>'
        1: from /home/xxxxx/.rvm/rubies/ruby-2.6.2/lib/ruby/site_ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
/home/xxxxx/.rvm/rubies/ruby-2.6.2/lib/ruby/site_ruby/2.6.0/rubygems.rb:284:in `find_spec_for_exe': can't find gem wpscan (>= 0.a) with executable wpscan (Gem::GemNotFoundException)
xxxxx@DESKTOP-xxxxx:~/wpscan$ sudo wpscan
One of the following options is required: url, update, help, hh, version

Please use --help/-h for the list of available options.
```
**How can I solve this problem?**

**Comment by FireFart** [comment]
refer to the readme
