### ISSUE TITLE
Scan Aborted: dynamic_finders.yml: checksums do not match

### ISSUE THREAD

**Issue by giacomotorricelli** [wpscanteam/wpscan#1387]
Tried with multiple instances, I get

```
ec2-user@kali:~$ wpscan --url acetaiasereni.it
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.6.3
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

Scan Aborted: dynamic_finders.yml: checksums do not match
Trace: /usr/share/rubygems-integration/all/gems/wpscan-3.6.3/lib/wpscan/db/updater.rb:148:in `block in update'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.3/lib/wpscan/db/updater.rb:138:in `each'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.3/lib/wpscan/db/updater.rb:138:in `update'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.3/app/controllers/core.rb:47:in `update_db'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.3/app/controllers/core.rb:57:in `before_scan'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.7/lib/cms_scanner/controllers.rb:44:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.7/lib/cms_scanner/controllers.rb:44:in `block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.7/lib/cms_scanner/controllers.rb:43:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.7/lib/cms_scanner/scan.rb:24:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.3/bin/wpscan:16:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.7/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.3/bin/wpscan:6:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.3/bin/wpscan:6:in `<top (required)>'
/usr/bin/wpscan:23:in `load'
/usr/bin/wpscan:23:in `<main>'
```

That's my trace

```
ec2-user@kali:~$ curl 'https://data.wpscan.org/cdn-cgi/trace'
fl=52f39
h=data.wpscan.org
ip=34.255.157.208
ts=1567505489.48
visit_scheme=https
uag=curl/7.65.3
colo=DUB
http=http/2
loc=IE
tls=TLSv1.3
sni=plaintext
warp=off

```

**Comment by erwanlr** [comment]
Could you try again ? we had some issues with our CDN

**Comment by giacomotorricelli** [comment]
Seems to be ok, thanks.
