### ISSUE TITLE
4409: from /root/gems/bin/wpscan:23:in `<main>'

### ISSUE THREAD

**Issue by Lerie82** [wpscanteam/wpscan#1419]
```
Traceback (most recent call last):
        4409: from /root/gems/bin/wpscan:23:in `<main>'
        4408: from /root/gems/bin/wpscan:23:in `load'
        4407: from /root/gems/gems/wpscan-3.7.3/bin/wpscan:4:in `<top (required)>'
        4406: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        4405: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        4404: from /root/gems/gems/wpscan-3.7.3/lib/wpscan.rb:8:in `<top (required)>'
        4403: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        4402: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         ... 4397 levels...
           4: from /root/gems/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
           3: from /root/gems/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
           2: from /root/gems/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
           1: from /root/gems/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
/root/gems/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError)
```

### Environment
* Version of Ruby: ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux-gnu]
* Operating System (OS): Linux localhost 3.18.0-19733-g972ff9adcd38 #1 SMP PREEMPT Wed Sep 25 23:34:42 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux (ChromeOS)

I could not get wpscan installed with ruby2.3 so i updated to 2.5

**Comment by erwanlr** [comment]
Seems like it's related to https://github.com/rails/rails/issues/25125, update the `activesupport` gem (to something > 4.2.7.1) and try again
