### ISSUE TITLE
Scan Aborted: wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by gianogli** [wpscanteam/wpscan#1429]
### Subject of the issue
All the scans I tried with the last version are aborted due this error:
```
Scan Aborted: wrong number of arguments (given 1, expected 0)
Trace: /var/lib/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/core_ext/string/inflections.rb:107:in `titleize'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/finders/finder.rb:65:in `block in found_by'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/finders/finder.rb:60:in `each'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/finders/finder.rb:60:in `found_by'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/app/finders/interesting_findings/headers.rb:10:in `passive'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/finders/base_finders.rb:31:in `run_finder'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/finders/independent_finders.rb:18:in `block (2 levels) in run'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/finders/independent_finders.rb:17:in `each'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/finders/independent_finders.rb:17:in `block in run'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/finders/independent_finders.rb:16:in `each'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/finders/independent_finders.rb:16:in `run'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/finders/independent_finder.rb:21:in `find'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/finders/independent_finder.rb:12:in `find'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/target.rb:28:in `interesting_findings'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/app/controllers/interesting_findings.rb:19:in `run'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/controllers.rb:50:in `each'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/controllers.rb:50:in `block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/controllers.rb:45:in `run'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/scan.rb:24:in `run'
/var/lib/gems/2.5.0/gems/wpscan-3.7.5/bin/wpscan:17:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/cms_scanner-0.7.1/lib/cms_scanner/scan.rb:15:in `initialize'
/var/lib/gems/2.5.0/gems/wpscan-3.7.5/bin/wpscan:6:in `new'
/var/lib/gems/2.5.0/gems/wpscan-3.7.5/bin/wpscan:6:in `<top (required)>'
/usr/local/bin/wpscan:23:in `load'
/usr/local/bin/wpscan:23:in `<main>'
```

### Your environment
* Version of WPScan: 3.7.5
* Version of Ruby: 2.5.2
* Operating System (OS): Debian (testing)

### Steps to reproduce
I simply run "wpscan --url mywebsite.com"

### What have you already tried
-) update wpscan to the last version
-) remove and reinstall wpscan

Things you have tried (where relevant):

* Update WPScan to the latest version [X]
* Update Ruby to the latest version [X]
* Ensure you can reach the target site using cURL [X]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [ ]

**Comment by erwanlr** [comment]
Update the activesupport gem (version > 4.2 is required) => `gem update activesupport`

I wonder how the correct version was not installed as we do that in the dependencies:
- https://github.com/wpscanteam/OptParseValidator/blob/master/opt_parse_validator.gemspec#L23
- https://github.com/wpscanteam/CMSScanner/blob/master/cms_scanner.gemspec#L24

What's the version of the opt_parse_validator gem installed ? `gem list opt_parse_validator`

**Comment by gianogli** [comment]
```
# gem update activesupport
Updating installed gems
Updating activesupport
Fetching: zeitwerk-2.2.1.gem (100%)
Successfully installed zeitwerk-2.2.1
Fetching: activesupport-6.0.1.gem (100%)
Successfully installed activesupport-6.0.1
Parsing documentation for zeitwerk-2.2.1
Installing ri documentation for zeitwerk-2.2.1
Installing darkfish documentation for zeitwerk-2.2.1
Parsing documentation for activesupport-6.0.1
Installing ri documentation for activesupport-6.0.1
Installing darkfish documentation for activesupport-6.0.1
Done installing documentation for zeitwerk, activesupport after 4 seconds
Parsing documentation for activesupport-6.0.1
Parsing documentation for zeitwerk-2.2.1
Done installing documentation for activesupport, zeitwerk after 1 seconds
Gems updated: activesupport zeitwerk
```
And now it's working! Thanks!

Here the version of  opt_parse_validator gem:
```
# gem list opt_parse_validator

*** LOCAL GEMS ***

opt_parse_validator (1.8.1, 1.8.0, 0.0.17.0)
```

**Comment by erwanlr** [comment]
Thanks :)
