### ISSUE TITLE
can Aborted: metadata.json: checksums do not match

### ISSUE THREAD

**Issue by etx77** [wpscanteam/wpscan#1477]
Can't update db 
Linux zetareticuli 5.4.0-kali4-amd64 #1 SMP Debian 5.4.19-1kali1 (2020-02-17) x86_64 GNU/Linux
ii  wpscan     3.7.11-0kali1      all          Black box WordPress vulnerability scanner
ii  ruby2.5     2.5.7-1+b1       amd64        Interpreter of object-oriented scripting language Ruby

root@zetareticuli:~# wpscan --update --verbose
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.7.11
                               
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

[i] Updating the Database ...

Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.
Trace: /var/lib/gems/2.5.0/gems/wpscan-3.7.11/lib/wpscan/db/updater.rb:151:in `block in update'
/var/lib/gems/2.5.0/gems/wpscan-3.7.11/lib/wpscan/db/updater.rb:141:in `each'
/var/lib/gems/2.5.0/gems/wpscan-3.7.11/lib/wpscan/db/updater.rb:141:in `update'
/var/lib/gems/2.5.0/gems/wpscan-3.7.11/app/controllers/core.rb:47:in `update_db'
/var/lib/gems/2.5.0/gems/wpscan-3.7.11/app/controllers/core.rb:57:in `before_scan'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.8.6/lib/cms_scanner/controllers.rb:46:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.8.6/lib/cms_scanner/controllers.rb:46:in `block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.8.6/lib/cms_scanner/controllers.rb:45:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.8.6/lib/cms_scanner/scan.rb:24:in `run'
/var/lib/gems/2.5.0/gems/wpscan-3.7.11/bin/wpscan:17:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.8.6/lib/cms_scanner/scan.rb:15:in `initialize'
/var/lib/gems/2.5.0/gems/wpscan-3.7.11/bin/wpscan:6:in `new'
/var/lib/gems/2.5.0/gems/wpscan-3.7.11/bin/wpscan:6:in `<top (required)>'
/usr/local/bin/wpscan:23:in `load'
/usr/local/bin/wpscan:23:in `<main>'
root@zetareticuli:~#

**Comment by etx77** [comment]
now work !!
