### ISSUE TITLE
wpscan not working while running through exec() command

### ISSUE THREAD

**Issue by jogeshpi03** [wpscanteam/wpscan#1514]
No problem if I run the wpscan through terminal but when i am getting the following issue while running wpscan through `exec('wpscan --update')` command. Could anyone please help me to resolve this issue?

```
Scan Aborted: Permission denied @ dir_s_mkdir - /usr/share/httpd/.wpscan
Trace: /usr/share/ruby/fileutils.rb:232:in `mkdir'
/usr/share/ruby/fileutils.rb:232:in `fu_mkdir'
/usr/share/ruby/fileutils.rb:210:in `block (2 levels) in mkdir_p'
/usr/share/ruby/fileutils.rb:208:in `reverse_each'
/usr/share/ruby/fileutils.rb:208:in `block in mkdir_p'
/usr/share/ruby/fileutils.rb:193:in `each'
/usr/share/ruby/fileutils.rb:193:in `mkdir_p'
/usr/local/share/gems/gems/wpscan-3.8.2/lib/wpscan/db/updater.rb:25:in `initialize'
/usr/local/share/gems/gems/wpscan-3.8.2/app/controllers/core.rb:24:in `new'
/usr/local/share/gems/gems/wpscan-3.8.2/app/controllers/core.rb:24:in `local_db'
/usr/local/share/gems/gems/wpscan-3.8.2/app/controllers/core.rb:53:in `before_scan'
/usr/local/share/gems/gems/cms_scanner-0.10.1/lib/cms_scanner/controllers.rb:46:in `each'
/usr/local/share/gems/gems/cms_scanner-0.10.1/lib/cms_scanner/controllers.rb:46:in `block in run'
/usr/share/ruby/timeout.rb:76:in `timeout'
/usr/local/share/gems/gems/cms_scanner-0.10.1/lib/cms_scanner/controllers.rb:45:in `run'
/usr/local/share/gems/gems/cms_scanner-0.10.1/lib/cms_scanner/scan.rb:24:in `run'
/usr/local/share/gems/gems/wpscan-3.8.2/bin/wpscan:17:in `block in <top (required)>'
/usr/local/share/gems/gems/cms_scanner-0.10.1/lib/cms_scanner/scan.rb:15:in `initialize'
```

**Comment by erwanlr** [comment]
You will have to manually create (and gives read/write permissions) the `/usr/share/httpd/.wpscan` folder then, which will contain the data files. Usually it's done automatically in `~/.wpscan`, but running through `exec` has a different home folder it seems.
