### ISSUE TITLE
MSYS2 on Windows with wpscan error

### ISSUE THREAD

**Issue by asorev** [wpscanteam/wpscan#1523]
### Subject of the issue
I have MSYS2 and wpscan installed.

But when I want to do something (like `wpscan --help`) it falls down with error:
```
Traceback (most recent call last):
        29: from /usr/local/bin/wpscan:23:in `<main>'
        28: from /usr/local/bin/wpscan:23:in `load'
        27: from /home/username/.gem/ruby/2.7.0/gems/wpscan-3.8.3/bin/wpscan:4:in `<top (required)>'
        26: from /usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        25: from /usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        24: from /home/username/.gem/ruby/2.7.0/gems/wpscan-3.8.3/lib/wpscan.rb:8:in `<top (required)>'
        23: from /usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        22: from /usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        21: from /home/username/.gem/ruby/2.7.0/gems/cms_scanner-0.12.0/lib/cms_scanner.rb:4:in `<top (required)>'
        20: from /usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        19: from /usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        18: from /home/username/.gem/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
        17: from /usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        16: from /usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        15: from /home/username/.gem/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon.rb:15:in `<top (required)>'
        14: from /usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        13: from /usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        12: from /home/username/.gem/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/curl.rb:8:in `<top (required)>'
        11: from /home/username/.gem/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/curl.rb:13:in `<module:Ethon>'
        10: from /home/username/.gem/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/curl.rb:27:in `<module:Curl>'
         9: from /usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         8: from /usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         7: from /home/username/.gem/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:1:in `<top (required)>'
         6: from /home/username/.gem/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
         5: from /home/username/.gem/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:3:in `<module:Curl>'
         4: from /home/username/.gem/ruby/2.7.0/gems/ffi-1.13.1/lib/ffi/library.rb:392:in `callback'
         3: from /home/username/.gem/ruby/2.7.0/gems/ffi-1.13.1/lib/ffi/library.rb:392:in `map'
         2: from /home/username/.gem/ruby/2.7.0/gems/ffi-1.13.1/lib/ffi/library.rb:392:in `block in callback'
         1: from /home/username/.gem/ruby/2.7.0/gems/ffi-1.13.1/lib/ffi/library.rb:589:in `find_type'
/home/username/.gem/ruby/2.7.0/gems/ffi-1.13.1/lib/ffi/types.rb:69:in `find_type': unable to resolve type 'size_t' (TypeError)
```

### Your environment
* Version of WPScan: 3.8.4
* Version of Ruby: 2.7
* Operating System (OS): MSYS2 on Windows

### Steps to reproduce
Execute any command with wpscan

### Expected behavior
Normal work.

### Actual behavior
TypeError on /.gem/ruby/2.7.0/gems/ffi-1.13.1/lib/ffi/types.rb:69.

**Comment by erwanlr** [comment]
`/home/username/.gem/ruby/2.7.0/gems/ffi-1.13.1/lib/ffi/types.rb:69:in `find_type': unable to resolve type 'size_t' (TypeError)` is an error on FFI side, not WPScan. So you will have to check on their side.
