### ISSUE TITLE
Wpscan not working with Proxychain

### ISSUE THREAD

**Issue by Tejpandya** [wpscanteam/wpscan#1530]
I'm using wpscan with

Version **3.5.3**
OS uname -r : **4.19.0-kali4-amd64**

Command I'm running 

`proxychains wpscan --url https://mylivesite.com 
`
verbose output

```
scan Aborted: The url supplied 'https://mylivesite.com/' seems to be down (Couldn't connect to server)
Trace: /usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/app/controllers/core.rb:42:in `check_target_availability'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/app/controllers/core.rb:59:in `before_scan'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:44:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:44:in `block in run'
/usr/lib/ruby/2.7.0/timeout.rb:78:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:43:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/scan.rb:24:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:16:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:6:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:6:in `<top (required)>'
/usr/bin/wpscan:23:in `load'
/usr/bin/wpscan:23:in `<main>'
```

Works well without proxychain. 
I've seen other related issue but none of them have answered.

**Comment by erwanlr** [comment]
Then it's probably an issue with your proxychains configuration. I would also use the `--disable-tls-checks` cli option with wpscan, just in case
