### ISSUE TITLE
wpscan not working: Scan Aborted: HTTP Error: https://wpscan.com/api/v3/status?version=3.8.10 (status: 403)

### ISSUE THREAD

**Issue by oscarandreu** [wpscanteam/wpscan#1579]
### Subject of the issue
Scan Aborted: HTTP Error: https://wpscan.com/api/v3/status?version=3.8.10 (status: 403)

### Your environment
* Version of WPScan: 3.8.10
* Version of Ruby: ruby 2.7.2p137
* Operating System (OS): Linux kali 5.9.0-kali4-amd64 #1 SMP Debian 5.9.11-1kali1 (2020-12-01) x86_64 GNU/Linux

### Steps to reproduce
wpscan  --url https://brainfuck.htb -v --api-token xxxxxxxxxxxxxxxxxxxxxxxx --disable-tls-checks    

### Expected behavior
Succesful scan

### Actual behavior

```
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.10
       Sponsored by Automattic - https://automattic.com/
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________


Scan Aborted: HTTP Error: https://wpscan.com/api/v3/status?version=3.8.10 (status: 403)
Trace: /usr/share/rubygems-integration/all/gems/wpscan-3.8.10/lib/wpscan/db/vuln_api.rb:32:in `get'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.10/lib/wpscan/db/vuln_api.rb:61:in `status'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.10/app/controllers/vuln_api.rb:20:in `before_scan'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.12.1/lib/cms_scanner/controllers.rb:46:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.12.1/lib/cms_scanner/controllers.rb:46:in `block in run'
/usr/lib/ruby/2.7.0/timeout.rb:78:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.12.1/lib/cms_scanner/controllers.rb:45:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.12.1/lib/cms_scanner/scan.rb:24:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.10/bin/wpscan:17:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.12.1/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.10/bin/wpscan:6:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.10/bin/wpscan:6:in `<top (required)>'
/usr/bin/wpscan:23:in `load'
/usr/bin/wpscan:23:in `<main>'
```
If I try to test the url
https://wpscan.com/api/v3/status?version=3.8.10
I got a 401 
{ "status": "unauthorized" }

**Comment by oscarandreu** [comment]
I was working without token, so I regenerate the token and it's working.
I guess that is not intuitive enough.

**Comment by oscarandreu** [comment]
It was working without token, so I regenerate the token and it's working.
I guess that is not intuitive enough.
