### ISSUE TITLE
Why homebrew can not install wpscan?

### ISSUE THREAD

**Issue by ssxcxS45XT** [wpscanteam/wpscan#1589]
https://github.com/wpscanteam/wpscan/wiki/WPScan-User-Documentation

The above page mentions the following. But it doesn't work. Is there any change in homebrew so that the above doc is outdated?

```
$ brew install wpscan
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from e5eb6a264 to 0648082d6.
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 17 formulae.
==> Updated Casks
Updated 17 casks.

==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "wpscan".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by erwanlr** [comment]
I've updated the command in the Wiki, however there is an issue with Nokogiri it seems and it's being tracked there https://github.com/wpscanteam/homebrew-tap/issues/2

**Comment by ssxcxS45XT** [comment]
It still doesn't work.

```
$ brew install wpscanteam/tap/wpscan
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

==> Installing wpscan from wpscanteam/tap
==> Downloading https://github.com/mistydemeo/wpscan/commit/eed763944642416cb5245b4e0cd281cb161122b4.patch?full_index=1
Already downloaded: /Users/pengy/Library/Caches/Homebrew/downloads/05c5889d325fe9fc0b8d565e0a14622ca069155b39aabad4b36e95a78c065413--eed763944642416cb5245b4e0cd281cb161122b4.patch
==> Downloading https://github.com/wpscanteam/wpscan/archive/v3.8.11.tar.gz
Already downloaded: /Users/pengy/Library/Caches/Homebrew/downloads/d9755ea8e5ecc77f8a2c1eef0431b0559fb310832ea936d1a27b46335217176c--wpscan-3.8.11.tar.gz
==> Patching
==> Applying eed763944642416cb5245b4e0cd281cb161122b4.patch
patching file lib/wpscan/db/updater.rb
==> gem install bundler
==> /usr/local/Cellar/wpscan/3.8.11/libexec/gems/bundler-2.2.4/exe/bundle install --jobs=16
Last 15 lines from /Users/pengy/Library/Logs/Homebrew/wpscan/02.bundle:

  /usr/local/Cellar/wpscan/3.8.11/libexec/ruby/3.0.0/extensions/x86_64-darwin-19/3.0.0/nokogiri-1.10.10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/Cellar/wpscan/3.8.11/libexec/ruby/3.0.0/gems/nokogiri-1.10.10 for inspection.
Results logged to /usr/local/Cellar/wpscan/3.8.11/libexec/ruby/3.0.0/extensions/x86_64-darwin-19/3.0.0/nokogiri-1.10.10/gem_make.out

An error occurred while installing nokogiri (1.10.10), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.10' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  wpscan was resolved to 3.8.11, which depends on
    cms_scanner was resolved to 0.12.1, which depends on
      nokogiri

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/wpscanteam/homebrew-tap/issues
```

**Comment by erwanlr** [comment]
See my previous message, highlighted in bold.

**Comment by ssxcxS45XT** [comment]
So basically `brew install wpscanteam/tap/wpscan` still can not be used due to the error of Nokogiri.

**Comment by erwanlr** [comment]
Unfortunately, yes

**Comment by erwanlr** [comment]
The issue has now been fixed

**Comment by ovuln** [comment]
How fix?
```
┌─(~)───────────────────────────────(xiangchen@ovuln:s001)─┐
└─(23:34:21)──> brew install wpscan            ──(五, 506)─┘
Warning: Building ruby from source as the bottle needs:
- HOMEBREW_CELLAR: /opt/homebrew/Cellar (yours is /Users/dark/homebrew/Cellar)
- HOMEBREW_PREFIX: /opt/homebrew (yours is /Users/dark/homebrew)
==> Downloading https://rubygems.org/rubygems/rubygems-3.3.11
Already downloaded: /Users/dark/Library/Caches/Homebrew/downloads/59ef2cf81d4e5a65435e511cdb583d771384dacc0d6e1a919efb5012c4261b05--rubygems-3.3.11.tgz
==> Downloading https://cache.ruby-lang.org/pub/ruby/3.1/ruby
Already downloaded: /Users/dark/Library/Caches/Homebrew/downloads/fafc7c035257faae96f55cfa022167b3ec8df66fe692de2d92b8e163c40139eb--ruby-3.1.2.tar.gz
==> Downloading https://github.com/wpscanteam/wpscan/archive/
Already downloaded: /Users/dark/Library/Caches/Homebrew/downloads/c686163da9885b9803fafc001e754bf4fd7a74100ebddbdd06dc97ca84ad230f--wpscan-3.8.22.tar.gz
==> Installing wpscan from wpscanteam/tap
==> Installing dependencies for wpscanteam/tap/wpscan: ruby
==> Installing wpscanteam/tap/wpscan dependency: ruby
==> ./configure --prefix=/Users/dark/homebrew/Cellar/ruby/3.1
==> make
==> make install
Last 15 lines from /Users/dark/Library/Logs/Homebrew/ruby/03.make:
	from /private/tmp/ruby-20220506-47076-fgcjpk/ruby-3.1.2/lib/rubygems/ext/builder.rb:195:in `block in build_extensions'
	from /private/tmp/ruby-20220506-47076-fgcjpk/ruby-3.1.2/lib/rubygems/ext/builder.rb:192:in `each'
	from /private/tmp/ruby-20220506-47076-fgcjpk/ruby-3.1.2/lib/rubygems/ext/builder.rb:192:in `build_extensions'
	from /private/tmp/ruby-20220506-47076-fgcjpk/ruby-3.1.2/lib/rubygems/installer.rb:853:in `build_extensions'
	from /private/tmp/ruby-20220506-47076-fgcjpk/ruby-3.1.2/lib/rubygems/installer.rb:328:in `install'
	from ./tool/rbinstall.rb:899:in `block in install'
	from ./tool/rbinstall.rb:713:in `no_write'
	from ./tool/rbinstall.rb:899:in `install'
	from ./tool/rbinstall.rb:1068:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:1043:in `foreach'
	from ./tool/rbinstall.rb:1043:in `block in <main>'
	from ./tool/rbinstall.rb:1127:in `block in <main>'
	from ./tool/rbinstall.rb:1124:in `each'
	from ./tool/rbinstall.rb:1124:in `<main>'
make: *** [do-install-all] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!
```
