### ISSUE TITLE
scan Aborted: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by Archurcl4w** [wpscanteam/wpscan#1646]
Before updating Kali Linux WPScan was running without any issues.
I recently updating Kali Lunux to 2021.1 after that I couldn't run WPScan any more.This issue was resolved by 
1. gem update
2. gem install wpscan 
3.wpscan --update

Current gem version on the system is 3.2.5

But after it I can't run any scan further with WPScan when giving commands every time like such 
wpscan --url example.com  --enumerate u 
or with any other arguments  having the following errors :-

scan Aborted: wrong number of arguments (given 2, expected 1)
Trace: /var/lib/gems/2.7.0/gems/psych-4.0.0/lib/psych.rb:322:in `safe_load'
/var/lib/gems/2.7.0/gems/wpscan-3.8.17/lib/wpscan/db/dynamic_finders/base.rb:14:in `all_df_data'
/var/lib/gems/2.7.0/gems/wpscan-3.8.17/lib/wpscan/db/dynamic_finders/wordpress.rb:9:in `df_data'
/var/lib/gems/2.7.0/gems/wpscan-3.8.17/lib/wpscan/db/dynamic_finders/wordpress.rb:51:in `versions_finders_configs'
/var/lib/gems/2.7.0/gems/wpscan-3.8.17/lib/wpscan/db/dynamic_finders/wordpress.rb:55:in `create_versions_finders'
/var/lib/gems/2.7.0/gems/wpscan-3.8.17/app/controllers/wp_version.rb:20:in `before_scan'
/var/lib/gems/2.7.0/gems/cms_scanner-0.13.4/lib/cms_scanner/controllers.rb:46:in `each'
/var/lib/gems/2.7.0/gems/cms_scanner-0.13.4/lib/cms_scanner/controllers.rb:46:in `block in run'
/var/lib/gems/2.7.0/gems/timeout-0.1.1/lib/timeout.rb:80:in `timeout'
/var/lib/gems/2.7.0/gems/cms_scanner-0.13.4/lib/cms_scanner/controllers.rb:45:in `run'
/var/lib/gems/2.7.0/gems/cms_scanner-0.13.4/lib/cms_scanner/scan.rb:24:in `run'
/var/lib/gems/2.7.0/gems/wpscan-3.8.17/bin/wpscan:17:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/cms_scanner-0.13.4/lib/cms_scanner/scan.rb:15:in `initialize'
/var/lib/gems/2.7.0/gems/wpscan-3.8.17/bin/wpscan:6:in `new'
/var/lib/gems/2.7.0/gems/wpscan-3.8.17/bin/wpscan:6:in `<top (required)>'
/usr/local/bin/wpscan:23:in `load'
/usr/local/bin/wpscan:23:in `<main>'

**Comment by 1Martinik** [comment]
Hello,

I think there is a problem with psych 4.0.0.
I had the same problem and I fixed it with these commands:
gem list --local | grep psych
sudo gem uninstall psych
sudo gem update psych --default

Cheers! :)

**Comment by Archurcl4w** [comment]
> 
> 
> Hello,
> 
> I think there is a problem with psych 4.0.0.
> I had the same problem and I fixed it with these commands:
> gem list --local | grep psych
> sudo gem uninstall psych
> sudo gem update psych --default
> 
> Cheers! :)

Thank you  1Martinik ! That is great and it fixed this issue for now finally.

**Comment by erwanlr** [comment]
The latest version of WPScan (3.8.17) fixed that so you don't have to the manual removal and install of `psych`

**Comment by alexsanford** [comment]
Closing this as it should be fixed in the latest version of wpscan
