### ISSUE TITLE
Scan Aborted: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by OOOlledj** [wpscanteam/wpscan#1651]
### Subject of the issue
Related to #1429, I met problem during scanning

### Your environment
* Version of WPScan: 3.8.17
* Version of Ruby: 3.0.1p64
* Operating System (OS): Linux Mint (Arch)
* Version of activesupport: 6.1.3.2
* Version of opt_parse_validator: 1.9.4

### Steps to reproduce
wpscan --url <my_website_url>

### Actual behavior

```
Scan Aborted: wrong number of arguments (given 2, expected 1)
Trace: /home/ooolledj/.local/share/gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych.rb:323:in 'safe_load'
/home/ooolledj/.local/share/gem/ruby/3.0.0/gems/wpscan-3.8.17/lib/wpscan/db/dynamic_finders/base.rb:14:in 'all_df_data'
/home/ooolledj/.local/share/gem/ruby/3.0.0/gems/wpscan-3.8.17/lib/wpscan/db/dynamic_finders/wordpress.rb:9:in 'df_data'
/home/ooolledj/.local/share/gem/ruby/3.0.0/gems/wpscan-3.8.17/lib/wpscan/db/dynamic_finders/wordpress.rb:51:in 'versions_finders_configs'
/home/ooolledj/.local/share/gem/ruby/3.0.0/gems/wpscan-3.8.17/lib/wpscan/db/dynamic_finders/wordpress.rb:55:in 'create_versions_finders'
/home/ooolledj/.local/share/gem/ruby/3.0.0/gems/wpscan-3.8.17/app/controllers/wp_version.rb:20:in 'before_scan'
/home/ooolledj/.local/share/gem/ruby/3.0.0/gems/cms_scanner-0.13.4/lib/cms_scanner/controllers.rb:46:in 'each'
/home/ooolledj/.local/share/gem/ruby/3.0.0/gems/cms_scanner-0.13.4/lib/cms_scanner/controllers.rb:46:in 'block in run'
/usr/lib/ruby/3.0.0/timeout.rb:80:in 'timeout'
/home/ooolledj/.local/share/gem/ruby/3.0.0/gems/cms_scanner-0.13.4/lib/cms_scanner/controllers.rb:45:in 'run'
/home/ooolledj/.local/share/gem/ruby/3.0.0/gems/cms_scanner-0.13.4/lib/cms_scanner/scan.rb:24:in 'run'
/home/ooolledj/.local/share/gem/ruby/3.0.0/gems/wpscan-3.8.17/bin/wpscan:17:in 'block in <top (required)>'
/home/ooolledj/.local/share/gem/ruby/3.0.0/gems/cms_scanner-0.13.4/lib/cms_scanner/scan.rb:15:in 'initialize'
/home/ooolledj/.local/share/gem/ruby/3.0.0/gems/wpscan-3.8.17/bin/wpscan:6:in 'new'
/home/ooolledj/.local/share/gem/ruby/3.0.0/gems/wpscan-3.8.17/bin/wpscan:6:in '<top (required)>'
/home/ooolledj/.local/share/gem/ruby/3.0.0/bin/wpscan:23:in 'load'
/home/ooolledj/.local/share/gem/ruby/3.0.0/bin/wpscan:23:in '<main>'
```

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.

Things you have tried (where relevant):

* Update WPScan to the latest version [X ]
* Update Ruby to the latest version [ X]
* Ensure you can reach the target site using cURL [X ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ X]
With HTTP proxy and --ignore-main-redirect i receive: "Scan Aborted: The remote website is up, but does not seem to be running WordPress."
* Ensure you are using a supported Operating System (Linux and macOS) [X ]

**Comment by erwanlr** [comment]
See https://github.com/wpscanteam/wpscan/issues/1646#issuecomment-846385059
