### ISSUE TITLE
Scan with --ignore-main-redirect option    not working.

### ISSUE THREAD

**Issue by cocoonkid** [wpscanteam/wpscan#1662]
I cannot get any scans from 3.8.18

it works only  when removing the --ignore-main-redirect option   

```
Scan Aborted: undefined method `+' for nil:NilClass
Trace: /opt/wpscan/vendor/bundle/ruby/3.0.0/gems/cms_scanner-0.13.5/lib/cms_scanner/target/scope.rb:53:in `scope_url_pattern'
/opt/wpscan/lib/wpscan/target/platform/wordpress/custom_directories.rb:20:in `content_dir'
/opt/wpscan/lib/wpscan/target/platform/wordpress.rb:106:in `wordpress_hosted?'
/opt/wpscan/app/controllers/core.rb:70:in `check_wordpress_state'
/opt/wpscan/app/controllers/core.rb:61:in `before_scan'
/opt/wpscan/vendor/bundle/ruby/3.0.0/gems/cms_scanner-0.13.5/lib/cms_scanner/controllers.rb:46:in `each'
/opt/wpscan/vendor/bundle/ruby/3.0.0/gems/cms_scanner-0.13.5/lib/cms_scanner/controllers.rb:46:in `block in run'
/home/user/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:80:in `timeout'
/opt/wpscan/vendor/bundle/ruby/3.0.0/gems/cms_scanner-0.13.5/lib/cms_scanner/controllers.rb:45:in `run'
/opt/wpscan/vendor/bundle/ruby/3.0.0/gems/cms_scanner-0.13.5/lib/cms_scanner/scan.rb:24:in `run'
/opt/wpscan/bin/wpscan:17:in `block in <main>'
/opt/wpscan/vendor/bundle/ruby/3.0.0/gems/cms_scanner-0.13.5/lib/cms_scanner/scan.rb:15:in `initialize'
/opt/wpscan/bin/wpscan:6:in `new'
/opt/wpscan/bin/wpscan:6:in `<main>'
```

**Comment by erwanlr** [comment]
What did you provide in the `--url` option ? Can send us that by email if needed, contact at wpscan dot com

**Comment by cocoonkid** [comment]
just --url https:/wordpress.org  (knowing that this is not a wordpress instance, at least I assumed that)

**Comment by erwanlr** [comment]
Well, you are missing a `/` in that URL ^^, hence the issue when using `--ignore-main-redirect` as it will use the URL you provided (`https:/wordpress.org`) and not the corrected one (`https://wordpress.org/`)

**Comment by cocoonkid** [comment]
oh god. How embarassing. Sorry.

**Comment by erwanlr** [comment]
No worries hihi :D
