### ISSUE TITLE
Cant Update WPScan

### ISSUE THREAD

**Issue by mastercho** [wpscanteam/wpscan#1676]
ruby --version
ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]

Windows 10

wpscan --update --verbose

````
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.6

       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

[i] Updating the Database ...

Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.
Trace: C:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/wpscan-3.8.6/lib/wpscan/db/updater.rb:150:in `block in update'
C:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/wpscan-3.8.6/lib/wpscan/db/updater.rb:141:in `each'
C:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/wpscan-3.8.6/lib/wpscan/db/updater.rb:141:in `update'
C:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/wpscan-3.8.6/app/controllers/core.rb:47:in `update_db'
C:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/wpscan-3.8.6/app/controllers/core.rb:57:in `before_scan'
C:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/cms_scanner-0.12.1/lib/cms_scanner/controllers.rb:46:in `each'
C:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/cms_scanner-0.12.1/lib/cms_scanner/controllers.rb:46:in `block in run'
C:/metasploit-framework/embedded/lib/ruby/2.6.0/timeout.rb:76:in `timeout'
C:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/cms_scanner-0.12.1/lib/cms_scanner/controllers.rb:45:in `run'
C:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/cms_scanner-0.12.1/lib/cms_scanner/scan.rb:24:in `run'
C:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/wpscan-3.8.6/bin/wpscan:17:in `block in <top (required)>'
C:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/cms_scanner-0.12.1/lib/cms_scanner/scan.rb:15:in `initialize'
C:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/wpscan-3.8.6/bin/wpscan:6:in `new'
C:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/wpscan-3.8.6/bin/wpscan:6:in `<top (required)>'
C:/metasploit-framework/embedded/bin/wpscan:23:in `load'
C:/metasploit-framework/embedded/bin/wpscan:23:in `<main>'
````

>curl -s data.wpscan.org/themes.json | sha512sum
ea85ebf524b655672b32c2ef09f178f11ce03979ab6084c8bbe769ade162605e133679d854643636483a73a82763d2e40848e212e8fa571ae1f7c6d4b04ba862 *-

Its since month like that

**Comment by FireFart** [comment]
Everything looks ok from here so I would guess it's a problem on your side. You can try to intercept the requests with a proxy and look at the response returned, maybe cloudflare is blocking your ip.

**Comment by mastercho** [comment]
1 year later issue still exists, any solutions? Its not IP block issue because i tried 5 locations from VPN none works and CF says owners fault https://community.cloudflare.com/t/community-tip-access-was-denied-error-code-1020/66439 if @firefart can you look into this would be great. I did clean install up to latest version 3.8.22 but nothing changed
