### ISSUE TITLE
cannot load such file -- json

### ISSUE THREAD

**Issue by PabloMartinMoreno** [wpscanteam/wpscan#1836]
I can't run wpscan; I'm getting the following error:

`
/opt/wpscan/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/core_ext/object/json.rb:4:in `require': cannot load such file -- json (LoadError)
        from /opt/wpscan/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/core_ext/object/json.rb:4:in `<top (required)>'
        from /opt/wpscan/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/core_ext/object.rb:13:in `require'
        from /opt/wpscan/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/core_ext/object.rb:13:in `<top (required)>'
        from /opt/wpscan/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/core_ext.rb:4:in `require'
        from /opt/wpscan/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/core_ext.rb:4:in `block in <top (required)>'
        from /opt/wpscan/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/core_ext.rb:3:in `each'
        from /opt/wpscan/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/core_ext.rb:3:in `<top (required)>'
        from /opt/wpscan/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/all.rb:5:in `require'
        from /opt/wpscan/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/all.rb:5:in `<top (required)>'
        from /opt/wpscan/lib/wpscan.rb:7:in `require'
        from /opt/wpscan/lib/wpscan.rb:7:in `<top (required)>'
        from /opt/wpscan/bin/wpscan:4:in `require'
        from /opt/wpscan/bin/wpscan:4:in `<main>'
`

I'm using the latest version of wpscan and ruby-json 2.7.1-1, which seems to be causing the error. I'm using Arch Linux.

**Comment by Rahim7X** [comment]
same issue in arch linux. Works on debian

**Comment by uhtred-X** [comment]
Yeah Same for me in Arch, tried wpsan-git as well but same error again. Also tried installation of all gems mentioned in error but no luck.

**Comment by Grelo4ka** [comment]
I face the same issue on Arch. Works fine once installed with `gem install`

**Comment by uhtred-X** [comment]
Yeah with 'gem install wpscan' things are working good now.

**Comment by Grelo4ka** [comment]
The problem is still there when installing wpscan from Arch Linux repos

**Comment by erwanlr** [comment]
That's something you will have to check with Arch linux by opening an issue on their side
