### ISSUE TITLE
Scan Aborted: wrong constant name/ Version_finder_module.const_set(constant_name, Module.new) ERROR 

### ISSUE THREAD

**Issue by SathruwanCooray** [wpscanteam/wpscan#1846]
![348379084-d5f368c4-21fd-420d-9555-b3f38d531318](https://github.com/user-attachments/assets/f858e837-5c84-4312-a8a3-628a9cfa8170)

Got this error when I was trying to run WPScan.

**Comment by podlisk** [comment]
Started to receive the same error as above. It was running ok up until just a couple of months ago.

WPScan Version 3.8.25

Error:
```
Scan Aborted: wrong constant name

            version_finder_module.const_set(constant_name, Module.new)
                                 ^^^^^^^^^^
Trace: /usr/share/rubygems-integration/all/gems/wpscan-3.8.25/lib/wpscan/db/dynamic_finders/plugin.rb:70:in `const_set'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.25/lib/wpscan/db/dynamic_finders/plugin.rb:70:in `maybe_create_module'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.25/lib/wpscan/db/dynamic_finders/plugin.rb:83:in `create_versions_finders'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.25/app/finders/plugin_version.rb:23:in `create_and_load_dynamic_versions_finders'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.25/app/finders/plugin_version.rb:16:in `initialize'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.9/lib/cms_scanner/finders/independent_finder.rb:12:in `new'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.9/lib/cms_scanner/finders/independent_finder.rb:12:in `find'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.25/app/models/plugin.rb:34:in `version'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.25/app/controllers/enumeration/enum_methods.rb:79:in `each'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.25/app/controllers/enumeration/enum_methods.rb:79:in `enum_plugins'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.25/app/controllers/enumeration.rb:13:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.9/lib/cms_scanner/controllers.rb:50:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.9/lib/cms_scanner/controllers.rb:50:in `block in run'
/usr/lib/ruby/3.1.0/timeout.rb:84:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.9/lib/cms_scanner/controllers.rb:45:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.9/lib/cms_scanner/scan.rb:24:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.25/bin/wpscan:17:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.9/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.25/bin/wpscan:6:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.25/bin/wpscan:6:in `<top (required)>'
/usr/bin/wpscan:25:in `load'
/usr/bin/wpscan:25:in `<main>'
```

**Comment by erwanlr** [comment]
- Does that happen with all sites or just a specific one ?
- Did you try upgrading to the latest version (3.8.27) ?

**Comment by Citvej** [comment]
Getting the same issue when running the following command
`wpscan --url https://boostbuddy.io -e vp --api-token wzlarrFKrWaSjWrHshHbBiZ5u1rRzVjAxna6ivTaXs0 --random-user-agent --ignore-main-redirect --stealthy`

`Trace: /opt/homebrew/Cellar/wpscan/3.8.22/libexec/lib/wpscan/db/dynamic_finders/plugin.rb:70:in `const_set'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/lib/wpscan/db/dynamic_finders/plugin.rb:70:in `maybe_create_module'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/lib/wpscan/db/dynamic_finders/plugin.rb:83:in `create_versions_finders'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/app/finders/plugin_version.rb:23:in `create_and_load_dynamic_versions_finders'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/app/finders/plugin_version.rb:16:in `initialize'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/ruby/3.2.0/gems/cms_scanner-0.13.8/lib/cms_scanner/finders/independent_finder.rb:12:in `new'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/ruby/3.2.0/gems/cms_scanner-0.13.8/lib/cms_scanner/finders/independent_finder.rb:12:in `find'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/app/models/plugin.rb:34:in `version'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/app/controllers/enumeration/enum_methods.rb:79:in `each'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/app/controllers/enumeration/enum_methods.rb:79:in `enum_plugins'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/app/controllers/enumeration.rb:13:in `run'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/ruby/3.2.0/gems/cms_scanner-0.13.8/lib/cms_scanner/controllers.rb:50:in `each'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/ruby/3.2.0/gems/cms_scanner-0.13.8/lib/cms_scanner/controllers.rb:50:in `block in run'
/opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/timeout.rb:173:in `timeout'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/ruby/3.2.0/gems/cms_scanner-0.13.8/lib/cms_scanner/controllers.rb:45:in `run'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/ruby/3.2.0/gems/cms_scanner-0.13.8/lib/cms_scanner/scan.rb:24:in `run'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/bin/wpscan:17:in `block in <top (required)>'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/ruby/3.2.0/gems/cms_scanner-0.13.8/lib/cms_scanner/scan.rb:15:in `initialize'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/bin/wpscan:6:in `new'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/bin/wpscan:6:in `<top (required)>'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/ruby/3.2.0/bin/wpscan:25:in `load'
/opt/homebrew/Cellar/wpscan/3.8.22/libexec/ruby/3.2.0/bin/wpscan:25:in `<main>'`

**Comment by Initsogar** [comment]
Hey all! I just took a look and can confirm this issue  affects v3.8.25 and earlier when scanning sites with plugins or themes that have non-Latin character slugs. Using v3.8.26 or later resolves the issue.

Duplicate of #1771, fixed in #1814.
