### ISSUE TITLE
LoadError ffi_c

### ISSUE THREAD

**Issue by MikeHorn-git** [wpscanteam/wpscan#1873]
Hello,

### Subject of the issue

```
cannot load such file -- ffi_c (LoadError)
Did you mean?  ffi
```

### Your environment

* Version of WPScan:
* Version of Ruby: 3.3.5
* Operating System (OS): ArchLinux
* Libffi : 3.4.6-1

### Steps to reproduce

```bash
Sudo pacman -S wpscan
wpscan --version
```

### Actual behavior

```bash
wpscan --version
/usr/lib/ruby/3.3.0/json/common.rb:3: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
/usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `require': cannot load such file -- ffi_c (LoadError)
Did you mean?  ffi
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /opt/wpscan/vendor/bundle/ruby/3.3.0/gems/ffi-1.17.0-x86_64-linux-gnu/lib/ffi.rb:5:in `rescue in <top (required)>'
	from /opt/wpscan/vendor/bundle/ruby/3.3.0/gems/ffi-1.17.0-x86_64-linux-gnu/lib/ffi.rb:2:in `<top (required)>'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /opt/wpscan/vendor/bundle/ruby/3.3.0/gems/ethon-0.16.0/lib/ethon.rb:3:in `<top (required)>'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /opt/wpscan/vendor/bundle/ruby/3.3.0/gems/typhoeus-1.4.1/lib/typhoeus.rb:2:in `<top (required)>'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /opt/wpscan/vendor/bundle/ruby/3.3.0/gems/cms_scanner-0.14.3/lib/cms_scanner.rb:4:in `<top (required)>'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /opt/wpscan/lib/wpscan.rb:8:in `<top (required)>'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /opt/wpscan/bin/wpscan:4:in `<main>'
/usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `require': cannot load such file -- 3.3/ffi_c (LoadError)
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /opt/wpscan/vendor/bundle/ruby/3.3.0/gems/ffi-1.17.0-x86_64-linux-gnu/lib/ffi.rb:3:in `<top (required)>'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /opt/wpscan/vendor/bundle/ruby/3.3.0/gems/ethon-0.16.0/lib/ethon.rb:3:in `<top (required)>'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /opt/wpscan/vendor/bundle/ruby/3.3.0/gems/typhoeus-1.4.1/lib/typhoeus.rb:2:in `<top (required)>'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /opt/wpscan/vendor/bundle/ruby/3.3.0/gems/cms_scanner-0.14.3/lib/cms_scanner.rb:4:in `<top (required)>'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /opt/wpscan/lib/wpscan.rb:8:in `<top (required)>'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /usr/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /opt/wpscan/bin/wpscan:4:in `<main>'
```

**Comment by 0xl30** [comment]
facing same issue in arch linux.
