### ISSUE TITLE
Error updating Malware.txt

### ISSUE THREAD

**Issue by osok** [wpscanteam/wpscan#733]
wpscan will not run because it appears tofail during the updating ofr the malwares.txt.  I'm not sure if the checksum is failing or if it cannot get to a file.  I tried to get tothe URL in question and I get 404.  Even if I lok for in the main fork of the vulndb under wpscanstream the master directory doesn't exist.

I'm running kali linux, with update and upgrade as of 12/6/2014

```
root@kali-vm:~/lab/public/251# ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
```

```
root@kali-vm:~/lab/public/251# wpscan --update --verbose
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.5.1
     Sponsored by the RandomStorm Open Source Initiative
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[+] Checking local_vulnerable_files.xml
  [i] Already Up-To-Date
[+] Checking local_vulnerable_files.xsd
  [i] Already Up-To-Date
[+] Checking malwares.txt
  [i] Restoring Backup due to error

Unable to get https://raw.githubusercontent.com/wpscanteam/vulndb/master/malwares.txt.sha512
Trace:
/usr/share/wpscan/lib/common/db_updater.rb:39:in `remote_file_checksum'
/usr/share/wpscan/lib/common/db_updater.rb:85:in `block in update'
/usr/share/wpscan/lib/common/db_updater.rb:82:in `each'
/usr/share/wpscan/lib/common/db_updater.rb:82:in `update'
./wpscan.rb:48:in `main'
./wpscan.rb:404:in `<main>'
```

Even though it should not matter I tried runnig from the wpscan directory

```
root@kali-vm:/usr/share/wpscan# ruby ./wpscan.rb --update
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.5.1
     Sponsored by the RandomStorm Open Source Initiative
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

Unable to get https://raw.githubusercontent.com/wpscanteam/vulndb/master/malwares.txt.sha512
```

Obviously I'm reporting this because it breaks the function of wpscan, but in the short term all I need to do is enumerate users.  Is there a work around?

**Comment by adepentane** [comment]
Okay guys. When trying to run this on my machine, i got this error. Please kindly assist. Thanks.

Unable to get https://raw.githubusercontent.com/wpscanteam/vulndb/master/local_vulnerable_files.xml.sha512

And this is not allowing the WPscan to run. Please help. 
Email: adepentane5@gmail.com

**Comment by adepentane** [comment]
or if there is a manual way to update the database.

**Comment by FireFart** [comment]
@adepentane you're running a very old version of wpscan. Please download the current one or fetch it via git. You can find instructions over there https://github.com/wpscanteam/wpscan/blob/master/README.md
