### ISSUE TITLE
typhoeus issue

### ISSUE THREAD

**Issue by NinjaGlitch** [wpscanteam/wpscan#760]
command is 
wpscan --url lrservice.ru

error
/usr/lib/ruby/vendor_ruby/typhoeus/request.rb:199: stack level too deep (SystemStackError)

Using last version from github

**Comment by ethicalhack3r** [comment]
Can reproduce, full error:

```
/Users/ryan/.rvm/gems/ruby-2.2.0@wpscan/gems/typhoeus-0.7.0/lib/typhoeus/request.rb:204:in `block in hashable_string_for': stack level too deep (SystemStackError)
	from /Users/ryan/.rvm/gems/ruby-2.2.0@wpscan/gems/typhoeus-0.7.0/lib/typhoeus/request.rb:204:in `map'
	from /Users/ryan/.rvm/gems/ruby-2.2.0@wpscan/gems/typhoeus-0.7.0/lib/typhoeus/request.rb:204:in `hashable_string_for'
	from /Users/ryan/.rvm/gems/ruby-2.2.0@wpscan/gems/typhoeus-0.7.0/lib/typhoeus/request.rb:204:in `block in hashable_string_for'
	from /Users/ryan/.rvm/gems/ruby-2.2.0@wpscan/gems/typhoeus-0.7.0/lib/typhoeus/request.rb:204:in `map'
	from /Users/ryan/.rvm/gems/ruby-2.2.0@wpscan/gems/typhoeus-0.7.0/lib/typhoeus/request.rb:204:in `hashable_string_for'
	from /Users/ryan/.rvm/gems/ruby-2.2.0@wpscan/gems/typhoeus-0.7.0/lib/typhoeus/request.rb:202:in `hashable_string_for'
	from /Users/ryan/.rvm/gems/ruby-2.2.0@wpscan/gems/typhoeus-0.7.0/lib/typhoeus/request.rb:204:in `block in hashable_string_for'
	from /Users/ryan/.rvm/gems/ruby-2.2.0@wpscan/gems/typhoeus-0.7.0/lib/typhoeus/request.rb:204:in `map'
	 ... 7272 levels...
	from /Users/ryan/Tools/wpscan/lib/wpscan/wp_target.rb:73:in `login_url'
	from /Users/ryan/Tools/wpscan/lib/wpscan/wp_target.rb:54:in `wordpress?'
	from ./wpscan.rb:108:in `main'
	from ./wpscan.rb:415:in `<main>'
```

**Comment by ethicalhack3r** [comment]
The site you tried to scan doesn't seem to be running WordPress

**Comment by FireFart** [comment]
so we need to implement a infinite loop check

**Comment by NinjaGlitch** [comment]
ns records was changed, ill ask to return them for a while

**Comment by erwanlr** [comment]
There is one (maxredirs: 3), typhoeus also has one (maxredirs: 50)

**Comment by erwanlr** [comment]
oh, the redirection in the login_url is not checked with typhoeus, this is why it fails

**Comment by NinjaGlitch** [comment]
!
