### ISSUE TITLE
[ST2, Windows 7,x 64] Load error

### ISSUE THREAD

**Issue by Javix** [wpscanteam/wpscan#786]
I have a load error with the following nokogiri versions installed:
```
gem list nokogiri
nokogiri (1.6.6.2 x64-mingw32, 1.6.5 x64-mingw32)
```
Tried to load it irb:
```
C:\Users\XXXXXX\Documents\projects\ruby_drafts\lib>irb
irb(main):001:0> require 'nokogiri'
LoadError: cannot load such file -- nokogiri/nokogiri
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x64-mingw32/lib/nokogiri.rb:29:in `rescue
 in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x64-mingw32/lib/nokogiri.rb:25:in `<top (
required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1
        from C:/Ruby22-x64/bin/irb:11:in `<main>'
irb(main):002:0>
```
OS: Windows 7 Pro
Ruby: `ruby 2.2.1p85 (2015-02-26 revision 49769) [x64-mingw32]`

Any idea ? Thank you

**Comment by Javix** [comment]
Opened by error, sorry for that :)
