### ISSUE TITLE
"The target seems to be down", even though it's definitely up

### ISSUE THREAD

**Issue by binwiederhier** [wpscanteam/wpscan#790]
Hi there,

I get this when running against my blog (see profile).

```
$ ruby wpscan.rb --url http://<url>/ 
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.7
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[+] URL: http://<url>/
[+] Started: Wed Apr  1 00:51:11 2015

[+] robots.txt available under: 'http://<url>robots.txt'
[!] The WordPress 'http://<url>/readme.html' file exists exposing a version number

The target seems to be down
/home/user/wpscan/lib/wpscan/wpscan_helper.rb:124:in `block in <top (required)>': The target seems to be down (RuntimeError)
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:128:in `call'
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:128:in `block in execute_callbacks'
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:127:in `map'
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:127:in `execute_callbacks'
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/request/operations.rb:35:in `finish'
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/easy_factory.rb:129:in `block in set_callback'
	from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/easy/response_callbacks.rb:65:in `call'
	from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/easy/response_callbacks.rb:65:in `block in complete'
	from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/easy/response_callbacks.rb:65:in `each'
	from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/easy/response_callbacks.rb:65:in `complete'
	from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/multi/operations.rb:148:in `check'
	from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/multi/operations.rb:161:in `run'
	from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/multi/operations.rb:43:in `perform'
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/hydra/runnable.rb:15:in `run'
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/hydra/memoizable.rb:51:in `run'
	from wpscan.rb:412:in `ensure in main'
	from wpscan.rb:412:in `main'
	from wpscan.rb:416:in `<main>'
```

**Comment by ethicalhack3r** [comment]
Looks like the website is failing to respond to some requests. This could either be due to the web server not being able to handle the amount/speed of requests (doubtful in this case) or there's a WAF/IPS in place?

**Comment by erwanlr** [comment]
Requests to the potential config backup files are dropped, leading to 10 timed out requests and raising the down status

**Comment by erwanlr** [comment]
I've changed the default 10 timed out to 30, which fixes your issue :)

**Comment by ethicalhack3r** [comment]
:+1:

**Comment by RyanHartje** [comment]
I understand that this may have worked for you, but I still review it, and I confirmed that the default was set to 30. I have the most up to date wpscan and I still get:

```
[+] Enumerating installed plugins  ...

   Time: 00:01:15 <                                                                                                               > (21 / 2221)  0.94%  ETA: 02:11:46
The target seems to be down
/home/ryan/source/ruby/wpscan/lib/wpscan/wpscan_helper.rb:124:in `block in <top (required)>': The target seems to be down (RuntimeError)
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:128:in `call'
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:128:in `block in execute_callbacks'
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:127:in `map'
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:127:in `execute_callbacks'
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/request/operations.rb:35:in `finish'
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/easy_factory.rb:129:in `block in set_callback'
	from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/easy/response_callbacks.rb:65:in `call'
	from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/easy/response_callbacks.rb:65:in `block in complete'
	from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/easy/response_callbacks.rb:65:in `each'
	from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/easy/response_callbacks.rb:65:in `complete'
	from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/multi/operations.rb:148:in `check'
	from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/multi/operations.rb:161:in `run'
	from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/multi/operations.rb:43:in `perform'
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/hydra/runnable.rb:15:in `run'
	from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/hydra/memoizable.rb:51:in `run'
	from ./wpscan.rb:411:in `ensure in main'
	from ./wpscan.rb:411:in `main'
	from ./wpscan.rb:415:in `<main>'
```

**Comment by erwanlr** [comment]
Have you tried with the latest git version ?

There was an issue with the timeouts, which are now:
- 5s to establish the connection
- 1min for the complete transaction

In your case it might be the 5s which is too low, in this case, please try with --connect-timeout 20

**Comment by RyanHartje** [comment]
I only pulled down the project yesterday, but I did do a pull, and tried it again without --connect-timeout 20, which failed in the same way. 

When I supplied --connect-timeout 20, it failed immediately, with:
```
The WordPress URL supplied 'http://<url>' seems to be down.
```
