### ISSUE TITLE
'Undefined Method' error when targeting a non-WordPress site

### ISSUE THREAD

**Issue by pvdl** [wpscanteam/wpscan#791]
I got this error if when I use WPScan on a non-WordPress website:

```
undefined method ` ' for #<WpTarget:0x00000001db07a8>
```

**Comment by ethicalhack3r** [comment]
Can reproduce, full stack:

```
undefined method ` ' for #<WpTarget:0x007fe6f1a46520>
Trace:
/Users/ryan/Tools/wpscan/lib/wpscan/wp_target.rb:50:in `wordpress?'
./wpscan.rb:108:in `main'
./wpscan.rb:416:in `<main>'
```
