### ISSUE TITLE
"Target seems to be down" when enumerating plugins

### ISSUE THREAD

**Issue by dmchale** [wpscanteam/wpscan#794]
Hi, I'm trying to run wpscan for the first time and having trouble doing anything other than a basic passive scan. If I try to enumerate plugins, for example, I get through the initial portions of the scan and then it suddenly tells me the domain is not available. I tried on two different sites I control with two completely different setups (different DNS hosts, different web hosts, etc) and get the same thing for both domains. I followed the instructions on wpscan.org for my distro (Ubuntu 14.04+), running this on a vagrant install on my local windows pc. My *nix chops are close to nonexistent, and leave me scratching my head looking at the dump I'm getting when it fails.... I just know the target is most certainly NOT down, especially because the rest of the scan was JUST looking at the site.

Any thoughts?  TIA! 

```
==========================================================

ruby wpscan.rb --url www.mydomain.com --enumerate p
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 2.7
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[+] URL: http://www.mydomain.com/
[+] Started: Thu Apr  2 17:22:07 2015

[+] robots.txt available under: 'http://www.mydomain.com/robots.txt'
[+] Interesting header: CF-RAY: 1d0e36dced80087a-IAD
[+] Interesting header: LINK: <http://wp.me/4wtqp>; rel=shortlink, <https://www.mydomain.com/wp-json>; rel="https://github.com/WP-API/WP-API"
[+] Interesting header: SERVER: cloudflare-nginx
[+] Interesting header: X-CF-POWERED-BY: WP 1.3.16
[+] Interesting header: X-POWERED-BY: PleskLin

[+] WordPress version 4.1.1 identified from stylesheets numbers

[+] WordPress theme in use: flat-child-01

[+] Name: flat-child-01
 |  Location: http://www.mydomain.com/wp-content/themes/flat-child-01/
 |  Style URL: http://www.mydomain.com/wp-content/themes/flat-child-01/style.css
 |  Referenced style.css: /wp-content/themes/flat-child-01/style.css
 |  Description:

[+] Enumerating installed plugins  ...

   Time: 00:00:10 <                          > (21 / 2214)  0.94%  ETA: 00:17:34
The target seems to be down
/vagrant/wpscan/lib/wpscan/wpscan_helper.rb:124:in `block in <top (required)>': The target seems to be down (RuntimeError)
        from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:128:in `call'
        from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:128:in `block in execute_callbacks'
        from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:127:in `map'
        from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:127:in `execute_callbacks'
        from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/request/operations.rb:35:in `finish'
        from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/easy_factory.rb:129:in `block in set_callback'
        from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/easy/response_callbacks.rb:65:in `call'
        from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/easy/response_callbacks.rb:65:in `block in complete'
        from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/easy/response_callbacks.rb:65:in `each'
        from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/easy/response_callbacks.rb:65:in `complete'
        from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/multi/operations.rb:148:in `check'
        from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/multi/operations.rb:161:in `run'
        from /var/lib/gems/1.9.1/gems/ethon-0.7.3/lib/ethon/multi/operations.rb:43:in `perform'
        from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/hydra/runnable.rb:15:in `run'
        from /var/lib/gems/1.9.1/gems/typhoeus-0.7.1/lib/typhoeus/hydra/memoizable.rb:51:in `run'
        from wpscan.rb:412:in `ensure in main'
        from wpscan.rb:412:in `main'
        from wpscan.rb:416:in `<main>'
```

**Comment by erwanlr** [comment]
Could you re-run with the following options appended: ```--connect-timeout 20 --request-timeout 20```

It might also be due to a plugin  / WAF, if more than 30 requests timed out, wpscan raises this 'The target seems to be down'

**Comment by dmchale** [comment]
Cheers @erwanlr ! That seems to have fixed it, I'm now at 2+ minutes of enumeration, before it died at that 10-second mark. If it crashes again, I'll report back with whatever I see.

**Comment by erwanlr** [comment]
Ok, FYI the default connect-timeout is 2s, and request-timeout 4s, which seem too low in your case.

After your scan please retry with  --connect-timeout 10 --request-timeout 10 (or play with those until it doesn't raise the error) and let the enumeration run a few minutes. If it works, I will update the default values to those :)

**Comment by dmchale** [comment]
Everything ran successfully with 20's. I tried to run it with 10's, I just let it do its thing while I was doing other stuff on my machine, but it crashed after 1:55. I'll stick with forcing both of those parameters for now I guess, not a huge deal.

**Comment by erwanlr** [comment]
kk, thx :)

**Comment by shogunR** [comment]
Maybe i know where i can add this command " --connect-timeout 20 --request-timeout 20 "? Thanks

**Comment by soularrow93** [comment]
@shogunR  at the end of the original command
