### ISSUE TITLE
Error starting wpscan: uninitialized constant Nokogiri::VersionInfo::NOKOGIRI_LIBXML2_PATCHES

### ISSUE THREAD

**Issue by rogierg** [wpscanteam/wpscan#846]
Running latest wpscan on CentOS release 6.6 (Final)

```
Error:
./wpscan.rb
/opt/rh/ruby193/root/usr/local/share/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/version.rb:64:in `to_hash': uninitialized constant Nokogiri::VersionInfo::NOKOGIRI_LIBXML2_PATCHES (NameError)
        from /opt/rh/ruby193/root/usr/local/share/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/version.rb:99:in `<module:Nokogiri>'
        from /opt/rh/ruby193/root/usr/local/share/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/version.rb:1:in `<top (required)>'
        from /opt/rh/ruby193/root/usr/local/share/gems/gems/nokogiri-1.6.6.2/lib/nokogiri.rb:31:in `require'
        from /opt/rh/ruby193/root/usr/local/share/gems/gems/nokogiri-1.6.6.2/lib/nokogiri.rb:31:in `<top (required)>'
        from /usr/local/wpscan/lib/environment.rb:35:in `require'
        from /usr/local/wpscan/lib/environment.rb:35:in `<top (required)>'
        from /opt/rh/ruby193/root/usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
        from /opt/rh/ruby193/root/usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
        from /usr/local/wpscan/lib/common/common_helper.rb:50:in `<top (required)>'
        from /opt/rh/ruby193/root/usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
        from /opt/rh/ruby193/root/usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
        from /usr/local/wpscan/lib/wpscan/wpscan_helper.rb:3:in `<top (required)>'
        from /opt/rh/ruby193/root/usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
        from /opt/rh/ruby193/root/usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
        from ./wpscan.rb:8:in `<main>'

Nokogiri is installed and correct version:
*** LOCAL GEMS ***
nokogiri (1.6.6.2, 1.6.3.1)
```

**Comment by ethicalhack3r** [comment]
Can't reproduce on OS X using the same Nokogiri version.

Seems the error is here within Nokogiri:
```lib/nokogiri/version.rb:          hash_info['libxml']['libxml2_patches'] = NOKOGIRI_LIBXML2_PATCHES```

The ```NOKOGIRI_LIBXML2_PATCHES``` constant seems to be set in ```ext/nokogiri/nokogiri.c```

What version of libxml are you running? ```ls -l /usr/lib/libxml*```

**Comment by ethicalhack3r** [comment]
Also , what version of Ruby are you running?

**Comment by ethicalhack3r** [comment]
Closing due to no response

**Comment by rogierg** [comment]
Sorry for not getting back earlier, @ethicalhack3r

Fixed by changing the Gemfile
```source 'https://rubygems.org'

gem 'typhoeus', '~>0.7.0'
gem 'nokogiri', '<=1.6.3.1'
gem 'addressable'
gem 'json'
gem 'terminal-table', '~>1.4.5'
gem 'ruby-progressbar', '>=1.6.0'

group :test do
  gem 'webmock', '>=1.17.2'
  gem 'simplecov'
  gem 'rspec', '>=3.3.0'
  gem 'rspec-its'
end```

**Comment by Karanja-the-african-hippy** [comment]
I already figured out it thanks :) Had to open wpscan file as root user.
plus the file locations was diiferent from kali
