### ISSUE TITLE
Error in time to run a scan with wpscan

### ISSUE THREAD

**Issue by ReiGelado** [wpscanteam/wpscan#860]
I have a problem in time to run a scan with wpscan, I am using a ubuntu 15.04 and follow the tutorial wpscan.org installation.

Command:sudo ruby ~/wpscan/wpscan.rb --proxy SOCKS5://127.0.0.1:9050 -u host --enumerate u p vp tt t vt ap at --follow-redirection --max-threads 100 --batch --no-color -v

LOg:

_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.8
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[+] URL: http://host.com/
[+] Started: Sat Aug 29 14:30:30 2015

[!] The WordPress 'http://host.com/readme.html' file exists exposing a version number
[+] Interesting header: AGE: 27
[+] Interesting header: LINK: <http://host>; rel=shortlink
[+] Interesting header: SERVER: nginx/1.8.0
[+] Interesting header: VIA: 1.1 varnish
[+] Interesting header: X-CACHE: HIT
[+] Interesting header: X-VARNISH: 435115403 435115369
[+] XML-RPC Interface available under: http://host.com/xmlrpc.php
[!] Upload directory has directory listing enabled: http://host.com/wp-content/uploads/

[+] WordPress version 4.2.4 identified from meta generator

[!] No such file or directory @ rb_sysopen - /home/arthur/wpscan/data/wp_vulns.json
[!] Trace:
[!] /home/arthur/wpscan/lib/common/common_helper.rb:172:in `initialize'
/home/arthur/wpscan/lib/common/common_helper.rb:172:in `open'
/home/arthur/wpscan/lib/common/common_helper.rb:172:in `json'
/home/arthur/wpscan/lib/common/models/wp_item/vulnerable.rb:12:in `vulnerabilities'
/home/arthur/wpscan/lib/common/models/wp_version/output.rb:10:in `output'
/home/arthur/wpscan/wpscan.rb:230:in `main'
/home/arthur/wpscan/wpscan.rb:443:in `<main>'

**Comment by ReiGelado** [comment]
Already solved the problem, I had to manually extract the file data.zip
