### ISSUE TITLE
certain sites cause wpscan to stack trace

### ISSUE THREAD

**Issue by Viss** [wpscanteam/wpscan#943]
```
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.1
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] The remote host tried to redirect to: http://www.mydataangel.com/
[?] Do you want follow the redirection ? [Y]es [N]o [A]bort, default: [N]y
[+] URL: http://www.mydataangel.com/
[+] Started: Fri May 13 12:49:58 2016

[+] robots.txt available under: 'http://www.mydataangel.com/robots.txt'
[+] Interesting entry from robots.txt: http://www.mydataangel.com
[!] The WordPress 'http://www.mydataangel.com/readme.html' file exists exposing a version number
[!] Full Path Disclosure (FPD) in 'http://www.mydataangel.com/wp-includes/rss-functions.php': 
[+] Interesting header: AGE: 0
[+] Interesting header: X-BACKEND: all_requests
[+] Interesting header: X-CACHE: uncached
[+] Interesting header: X-CACHE-HIT: MISS
[+] Interesting header: X-CACHEABLE: YES:Forced
[+] Interesting header: X-PORT: port_10097
[+] XML-RPC Interface available under: http://www.mydataangel.com/xmlrpc.php

[!] undefined method `[]' for nil:NilClass
[!] Trace:
[!] /root/tools/wpscan/lib/common/models/wp_version.rb:44:in `metadata'
/root/tools/wpscan/lib/common/models/wp_version/output.rb:7:in `output'
./wpscan.rb:234:in `main'
./wpscan.rb:474:in `<main>'
```

**Comment by FireFart** [comment]
@Viss Looks like this is caused by the new wordpress release date information. Will investigate

**Comment by FireFart** [comment]
@Viss this was caused by the meta generator tag:
```
<meta name="generator" content="WordPress Download Manager 2.8.95" />
```
We identify this as a wordpress version which is not found in the JSON
