### ISSUE TITLE
I'm getting this error. How can I fix it?

### ISSUE THREAD

**Issue by backtr4ck** [wpscanteam/wpscan#947]
`/usr/lib/ruby/vendor_ruby/yajl/json_gem/encoding.rb:5:in `<top (required)>': uninitialized constant Yajl::Encoder (NameError)
Did you mean?  EncodingError
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/vendor_ruby/yajl/json_gem.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/wpscan/lib/environment.rb:34:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/wpscan/lib/common/common_helper.rb:45:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/wpscan/lib/wpscan/wpscan_helper.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./wpscan.rb:8:in `<main>'
`

**Comment by backtr4ck** [comment]
nvm, solved it by doing a bundle install
