### ISSUE TITLE
Invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by Sinderella** [wpscanteam/wpscan#957]
WPScan version:
```
Current version: 2.9.1
Last DB update: 2016-06-13
```

Ruby version:
```
# ruby --version
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
```

Trace:
```
[!] invalid byte sequence in UTF-8
[!] Trace:
[!] /usr/share/wpscan/lib/common/collections/wp_items/detectable.rb:98:in `scan'
/usr/share/wpscan/lib/common/collections/wp_items/detectable.rb:98:in `block in passive_detection'
/usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:187:in `block in each'
/usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:186:in `upto'
/usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:186:in `each'
/usr/share/wpscan/lib/common/collections/wp_items/detectable.rb:85:in `passive_detection'
/usr/share/wpscan/lib/common/collections/wp_plugins/detectable.rb:15:in `passive_detection'
./wpscan.rb:264:in `main'
./wpscan.rb:474:in `<main>'
```

I use it on clean install Kali. I think the problem is related to #892.

**Comment by FireFart** [comment]
@Sinderella would you like to share the url you scanned in private to team [at] wpscan.org so we can investigate? Thanks!

**Comment by Sinderella** [comment]
Sent!

**Comment by FireFart** [comment]
Thanks I'm able to reproduce the issue locally

**Comment by FireFart** [comment]
@Sinderella thx I've pushed a fix to the master branch for this one.

**Comment by jake-Merlin** [comment]
Im having the same issue
