### ISSUE TITLE
Update fails, plugins.json checksum

### ISSUE THREAD

**Issue by tjankov** [wpscanteam/wpscan#959]
Hi.

I cloned wpscan on ubuntu, bundle installed, trying to update database.
Im receiving checksum errors for plugins.json.

Here+s the --verbose output

```
[+] Checking plugins.json
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: 5da539a3c45c8db79e2a30bfd3cc314989811b4d193421696d6ccd2ac0b4cc7458963df8f139811bd77f2098bded08ed0268b493e8c661115de5859da38f74a2
  [i] Database File Checksum  : 2cf5a0bd2d1dbe832012089e7c76c48bbb641567e94d1bdac79c3d8e705e146064ddcefafe3c173addc72b03dd99f3bd9d6bd0cc84d5fe539c551a91afa3f883
  [i] Restoring Backup due to error

[!] plugins.json: checksums do not match (local: 5da539a3c45c8db79e2a30bfd3cc314989811b4d193421696d6ccd2ac0b4cc7458963df8f139811bd77f2098bded08ed0268b493e8c661115de5859da38f74a2 remote: 2cf5a0bd2d1dbe832012089e7c76c48bbb641567e94d1bdac79c3d8e705e146064ddcefafe3c173addc72b03dd99f3bd9d6bd0cc84d5fe539c551a91afa3f883)
[!] Trace:
[!] /home/t/wpscan/lib/common/db_updater.rb:104:in `block in update'
/home/t/wpscan/lib/common/db_updater.rb:84:in `each'
/home/t/wpscan/lib/common/db_updater.rb:84:in `update'
./wpscan.rb:73:in `main'
./wpscan.rb:474:in `<main>'

```

**Comment by ethicalhack3r** [comment]
This is being tracked here https://github.com/wpscanteam/wpscan/issues/958

Please use that thread to track this issue.

**Comment by tjankov** [comment]
That issue is closed..
Whats there to track?
Tell me how to fix the darn thing.

**Comment by ethicalhack3r** [comment]
> That issue is closed..
No. That issue is open. This issue is closed.

> Whats there to track?
The details of the issue. Errors, configurations, potential fixes.

> Tell me how to fix the darn thing.
We're working on it. But please feel free to go use something else if you're too impatient.

**Comment by tjankov** [comment]
Okay, you win. I deleted the comment :)
